load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/bzl/linux:release.bzl", "release")

oncall("antlir")

image.layer(
    name = "basic",
    default_os = "debian-trixie",
    features = [
        release.install(
            layer = ":basic",
            path = "/os-release",
            variant = "",
        ),
    ],
)
