load("//antlir/bzl:oss_shim.bzl", "thrift_library")
load("//metalos:defs.bzl", "rust_binary")

thrift_library(
    name = "test_if",
    languages = ["rust"],
    thrift_srcs = {"test_if.thrift": None},
)

rust_binary(
    name = "echo-generator",
    srcs = ["echo_generator.rs"],
    autocargo = {"ignore_rule": True},
    unittests = False,
    deps = [
        "anyhow",
        "fbthrift",
        ":test_if-rust",
    ],
)
