[true]
op = "added"

[true.diff]
mode = "u+rx,g+rx,o+rx"
file-type = "regular-file"
user = "root"
group = "root"
content-hash = "7880994991058629927"

["usr/lib/debug/.build-id"]
op = "added"

["usr/lib/debug/.build-id".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"

["usr/lib/debug/.build-id/cd"]
op = "added"

["usr/lib/debug/.build-id/cd".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"

["usr/lib/debug/.build-id/cd/ede5c8d904566a5cd33f0fdaff40eab44cdcd3.debug"]
op = "added"

["usr/lib/debug/.build-id/cd/ede5c8d904566a5cd33f0fdaff40eab44cdcd3.debug".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "regular-file"
user = "root"
group = "root"
content-hash = "10785375974688011570"
