load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir2_depgraph_if",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "nix",
        "serde",
        "static_assertions",
        "//antlir/antlir2/antlir2_features:antlir2_features",
    ],
)
