load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/features/dot_meta:dot_meta.bzl", "dot_meta")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")
load("//antlir/bzl:build_defs.bzl", "buck_sh_test", "internal_external")

# Normally, the `dot_meta` feature is included only when packaging up a final
# layer, but we want to make it easier to test with image_diff_test, so these
# layers explicitly include the `dot_meta` feature

oncall("antlir")

image.layer(
    name = "base",
    features = [
        dot_meta(),
    ],
)

image.layer(
    name = "dot_meta",
    features = [
        dot_meta(
            package_name = "foo",
            package_version = "bar",
            revision = "deadbeef",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "dot_meta-test",
    diff = internal_external(
        fb = "dot_meta.toml",
        oss = "dot_meta.oss.toml",
    ),
    diff_type = "file",
    layer = ":dot_meta",
)

image.layer(
    name = "unstamped",
)

package.cpio_gz(
    name = "stamped.cpio.gz",
    layer = ":unstamped",
)

buck_sh_test(
    name = "cpio-is-stamped",
    args = [
        "$(location :stamped.cpio.gz)",
        internal_external(
            fb = "fbcode//antlir/antlir2/features/dot_meta/tests:stamped.cpio.gz",
            oss = "antlir//antlir/antlir2/features/dot_meta/tests:stamped.cpio.gz",
        ),
    ],
    test = "test-cpio-is-stamped.sh",
)
