load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")

oncall("antlir")

feature.new(
    name = "features",
    features = [
        # Ensure that we don't end up with upstream dnf repos that might
        # interfere with the snapshot
        select({
            "//antlir/antlir2/os/package_manager:package_manager[apt]": None,
            "DEFAULT": feature.remove(
                must_exist = False,
                path = "/etc/yum.repos.d",
            ),
        }),
        select({
            "//antlir/antlir2/os/package_manager:package_manager[apt]": None,
            "DEFAULT": feature.remove(
                must_exist = False,
                path = "/etc/dnf/dnf.conf",
            ),
        }),
        feature.ensure_dirs_exist(dirs = "/__antlir2__"),
        feature.ensure_subdirs_exist(
            into_dir = "/__antlir2__",
            subdirs_to_create = "root",
        ),
        feature.ensure_subdirs_exist(
            into_dir = "/__antlir2__",
            subdirs_to_create = "build_appliance",
        ),
        feature.ensure_subdirs_exist(
            into_dir = "/__antlir2__",
            subdirs_to_create = "working_directory",
        ),
        feature.ensure_subdirs_exist(
            into_dir = "/__antlir2__",
            subdirs_to_create = "out",
        ),
        select({
            "//antlir/antlir2/os/package_manager:package_manager[apt]": "//antlir/antlir2/package_managers/apt/build_appliance:features",
            "DEFAULT": "//antlir/antlir2/package_managers/dnf/build_appliance:features",
        }),
    ],
    visibility = [
        "PUBLIC",
    ],
)
