load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")

feature.new(
    name = "features",
    features = [
        # Ensure that we don't end up with upstream dnf repos that might
        # interfere with the snapshot
        feature.remove(
            must_exist = False,
            path = "/etc/yum.repos.d",
        ),
        feature.remove(
            must_exist = False,
            path = "/etc/dnf/dnf.conf",
        ),
        feature.ensure_dirs_exist(dirs = "/__antlir2__"),
        feature.ensure_subdirs_exist(
            into_dir = "/__antlir2__",
            subdirs_to_create = "root",
        ),
        feature.ensure_subdirs_exist(
            into_dir = "/__antlir2__",
            subdirs_to_create = "build_appliance",
        ),
        "//antlir/antlir2/dnf:features",
    ],
    visibility = ["//antlir/antlir2/..."],
)
