load("//antlir/antlir2/features:defs.bzl", "feature_impl")

oncall("antlir")

feature_impl(
    name = "tarball",
    deps = [
        "flate2",
        "tar",
        "tracing",
        "zstd",
    ],
)
