use crate::path::VerifiedPath;

/// A marker trait indicating that this struct is actually
/// generated by the antlir image library
pub trait AntlirLayer {
    fn new_unchecked(base_path: VerifiedPath) -> Self;
}

#[macro_export]
macro_rules! generate_layer {
    ($name:ident { paths: $paths_type:ty $(,)* }) => {
        pub struct $name {
            pub paths: $paths_type,
        }

        impl $crate::layer::AntlirLayer for $name {
            fn new_unchecked(base_path: VerifiedPath) -> Self {
                Self {
                    paths: <$paths_type>::new_unchecked(base_path),
                }
            }
        }
    };
}
