load("//antlir/antlir2/bzl:configured_alias.bzl", "antlir2_configured_alias")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/testing:image_test.bzl", "image_python_test")
load("//antlir/bzl:build_defs.bzl", "cpp_binary", "cpp_library", "third_party")
load("//antlir/distro/platform:defs.bzl", "default_image_platform")
load("//antlir/distro/rpm:requires.bzl", "install_all_binary_rpm_requirements")

oncall("antlir")

prelude = native

cpp_binary(
    # @autodeps-skip
    name = "main",
    srcs = ["main.cpp"],
    # This should only be built for a centos system platform, use compatibility
    # attrs to guarantee that
    compatible_with = [
        "//antlir/distro:build-for-distro",
    ],
    default_target_platform = default_image_platform(),
    deps = [
        third_party.library(
            "jsoncpp",
            "jsoncpp",
            platform = "cxx",
        ),
        ":dep",
        ":platform-preprocessor-flags",
    ],
)

cpp_library(
    # @autodeps-skip
    name = "dep",
    srcs = ["dep.c"],
    headers = ["dep.h"],
    default_target_platform = default_image_platform(),
    deps = [
        third_party.library(
            "rpm",
            "librpm",
            platform = "cxx",
        ),
    ],
)

prelude.cxx_library(
    name = "platform-preprocessor-flags",
    # This should only be built for a centos system platform, use compatibility
    # attrs to guarantee that
    compatible_with = [
        "//antlir/distro:build-for-distro",
    ],
    default_target_platform = default_image_platform(),
    exported_platform_preprocessor_flags = [
        (
            "centos9-x86_64$",
            ['-DPLATFORM_PREPROCESSOR_FLAG="centos9-x86_64"'],
        ),
        (
            "centos10-x86_64$",
            ['-DPLATFORM_PREPROCESSOR_FLAG="centos10-x86_64"'],
        ),
        (
            "centos9-aarch64$",
            ['-DPLATFORM_PREPROCESSOR_FLAG="centos9-aarch64"'],
        ),
        (
            "centos10-aarch64$",
            ['-DPLATFORM_PREPROCESSOR_FLAG="centos10-aarch64"'],
        ),
    ],
)

image.layer(
    name = "main-rpm-layer",
    features = [
        feature.ensure_dirs_exist(dirs = "/test"),
        feature.install(
            src = ":main",
            dst = select({
                "//antlir/antlir2/os:centos10": "/test/main-for-centos10",
                "//antlir/antlir2/os:centos9": "/test/main-for-centos9",
            }),
            # Remove the libs symlink tree if it exists so that:
            # 1) there are no build-id conflicts
            # 2) rpm correctly identifies dependencies and does not think that
            #    this rpm provides the libs that it links against
            ignore_symlink_tree = True,
            never_use_dev_binary_symlink = True,
            transition_to_distro_platform = "yes-without-rpm-deps",
        ),
    ],
    target_compatible_with = select({
        "//antlir/antlir2/os:centos10": [],
        "//antlir/antlir2/os:centos9": [],
        "DEFAULT": ["antlir//antlir/distro:incompatible"],
    }),
)

# Package up the binary into an rpm so that RPM automatically finds the
# dependencies for system libraries and it can be safely installed into an image
package.rpm(
    name = "main-rpm",
    compatible_with = [
        "//antlir/antlir2/os:centos10",
        "//antlir/antlir2/os:centos9",
    ],
    layer = ":main-rpm-layer",
    license = "NONE",
    rpm_name = "main",
)

# We want to test a matrix of combinations:
# CentOS 9 x 10
# Binary installed via packaged RPM x Binary installed directly

image.layer(
    name = "test-layer-from-rpm",
    features = [
        feature.rpms_install(rpms = [
            "binutils",
            "coreutils",
        ]),
        feature.rpms_install(rpms = [":main-rpm"]),
    ],
)

image_python_test(
    name = "test-from-rpm",
    srcs = ["test.py"],
    default_os = "centos10",
    env = {
        "INSTALL_MODE": "rpm",
        "OS": select({
            "//antlir/antlir2/os:centos10": "centos10",
            "//antlir/antlir2/os:centos9": "centos9",
            "DEFAULT": "<NEVER USED>",
        }),
    },
    layer = ":test-layer-from-rpm",
)

antlir2_configured_alias(
    name = "test-c9-from-rpm",
    actual = ":test-from-rpm",
    default_os = "centos9",
)

image.layer(
    name = "test-layer-from-install",
    features = [
        feature.rpms_install(rpms = [
            "binutils",
            "coreutils",
        ]),
        feature.ensure_dirs_exist(dirs = "/test"),
        feature.install(
            src = ":main",
            dst = select({
                "//antlir/antlir2/os:centos10": "/test/main-for-centos10",
                "//antlir/antlir2/os:centos9": "/test/main-for-centos9",
            }),
            transition_to_distro_platform = True,
        ),
    ],
)

image_python_test(
    name = "test-from-install",
    srcs = ["test.py"],
    default_os = "centos10",
    env = {
        "INSTALL_MODE": "install",
        "OS": select({
            "//antlir/antlir2/os:centos10": "centos10",
            "//antlir/antlir2/os:centos9": "centos9",
            "DEFAULT": "<NEVER USED>",
        }),
    },
    layer = ":test-layer-from-install",
)

antlir2_configured_alias(
    name = "test-c9-from-install",
    actual = ":test-from-install",
    default_os = "centos9",
)

image.layer(
    name = "test-layer-from-global-query-pre",
    features = [
        feature.rpms_install(rpms = [
            "binutils",
            "coreutils",
        ]),
        feature.ensure_dirs_exist(dirs = "/test"),
        feature.install(
            src = ":main",
            dst = select({
                "//antlir/antlir2/os:centos10": "/test/main-for-centos10",
                "//antlir/antlir2/os:centos9": "/test/main-for-centos9",
            }),
            never_use_dev_binary_symlink = True,
            transition_to_distro_platform = "yes-without-rpm-deps",
        ),
    ],
)

image.layer(
    name = "test-layer-from-global-query",
    features = [
        install_all_binary_rpm_requirements(layer = ":test-layer-from-global-query-pre"),
    ],
    parent_layer = ":test-layer-from-global-query-pre",
)

image_python_test(
    name = "test-from-global-query",
    srcs = ["test.py"],
    default_os = "centos10",
    env = {
        "INSTALL_MODE": "global-query",
        "OS": select({
            "//antlir/antlir2/os:centos10": "centos10",
            "//antlir/antlir2/os:centos9": "centos9",
            "DEFAULT": "<NEVER USED>",
        }),
    },
    layer = ":test-layer-from-install",
)

antlir2_configured_alias(
    name = "test-c9-from-global-query",
    actual = ":test-from-global-query",
    default_os = "centos9",
)
