load("//antlir/antlir2/bzl:configured_alias.bzl", "antlir2_configured_alias")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/testing:image_test.bzl", "image_python_test")
load("//antlir/distro/platform:defs.bzl", "alias_for_current_image_platform", "default_image_platform")

oncall("antlir")

prelude = native

prelude.cxx_binary(
    # @autodeps-skip
    name = "main",
    srcs = ["main.cpp"],
    _cxx_toolchain = "//antlir/distro/toolchain/cxx:toolchain",
    # This should only be built for a centos system platform, use compatibility
    # attrs to guarantee that
    compatible_with = [
        "//antlir/distro:build-for-distro",
    ],
    default_target_platform = default_image_platform("centos9"),
    deps = [
        "//antlir/distro/deps:jsoncpp",
        "//antlir/distro/deps:libstdc++",
        "//antlir/distro/deps:rpm",
    ],
)

alias_for_current_image_platform(
    name = "main-for-os",
    actual = ":main",
)

image.layer(
    name = "main-rpm-layer",
    features = [
        feature.ensure_dirs_exist(dirs = "/test"),
        feature.install(
            src = ":main-for-os",
            dst = select({
                "//antlir/antlir2/os:centos10": "/test/main-for-centos10",
                "//antlir/antlir2/os:centos9": "/test/main-for-centos9",
            }),
            never_use_dev_binary_symlink = True,
        ),
    ],
    target_compatible_with = select({
        "//antlir/antlir2/os:centos10": [],
        "//antlir/antlir2/os:centos9": [],
        "DEFAULT": ["antlir//antlir/distro:incompatible"],
    }),
)

# Package up the binary into an rpm so that RPM automatically finds the
# dependencies for system libraries and it can be safely installed into an image
package.rpm(
    name = "main-rpm",
    compatible_with = [
        "//antlir/antlir2/os:centos10",
        "//antlir/antlir2/os:centos9",
    ],
    layer = ":main-rpm-layer",
    license = "NONE",
    rpm_name = "main",
)

image.layer(
    name = "test-layer",
    features = [
        feature.rpms_install(rpms = [
            "binutils",
            "coreutils",
        ]),
        feature.rpms_install(rpms = [":main-rpm"]),
    ],
)

image_python_test(
    name = "test",
    srcs = ["test.py"],
    default_os = "centos10",
    env = {
        "OS": select({
            "//antlir/antlir2/os:centos10": "centos10",
            "//antlir/antlir2/os:centos9": "centos9",
            "DEFAULT": "<NEVER USED>",
        }),
    },
    layer = ":test-layer",
)

antlir2_configured_alias(
    name = "test-c9",
    actual = ":test",
    default_os = "centos9",
)
