load("//antlir/bzl:build_defs.bzl", "rust_binary")

rust_binary(
    name = "antlir2_print_tree",
    srcs = glob(["src/*.rs"]),
    deps = [
        "clap",
        "walkdir",
        "//antlir/filesystem/stdio_path:stdio_path",
        "//antlir/staging/antlir2/antlir2_users:antlir2_users",
    ],
)
