omit_targets = []
extra_srcs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = 'Unresolved build script at vendor/anyhow-1.0.38/build.rs. Dependencies:'

[extra_mapped_srcs]

[platform_fixup]
