load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "udev_utils",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "gpt",
        "maplit",
        "slog_glog_fmt",
    ],
    unittests = [
        "vm",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "futures",
        "mio",
        "nix",
        "slog",
        "thiserror",
        "tokio",
        "tokio-stream",
        "udev",
    ],
)
