load("//antlir/antlir2/bzl/flavor:defs.bzl", "flavor")
load("//antlir/bzl:build_defs.bzl", "http_file")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/image:build_appliance.bzl", "build_appliance")

flavor(
    name = "centos9",
    default_build_appliance = ":build-appliance.prebuilt",
    default_dnf_repo_set = "generated//snapshot/rpm/centos9:repos",
    default_dnf_versionlock = "//antlir/antlir2/package_managers/dnf/build_appliance:empty-dnf-versionlock.json",
    visibility = ["PUBLIC"],
)

hash = "38f1ee19700466ff1a86e5cda92234c2a6ecd11d262ff39a429039b2d1ca97e1"

# Hand-built with. Will replace with a self-hosting antlir image after
# bootstrapping using this hand-built image
#
# $ cat dnf.conf
# [main]
# install_weak_deps=False
#
# [baseos]
# baseurl=https://mirror.facebook.net/centos-composes/9/CentOS-Stream-9-20240311.0/compose/BaseOS/x86_64/os/
#
# $ sudo dnf -c dnf.conf --installroot $(pwd)/root install dnf python3-dnf
http_archive(
    name = "build-appliance.tar.zst",
    urls = [
        "https://antlir.s3.us-east-2.amazonaws.com/build_appliance/" +
        "centos9_{}.tar.zst".format(hash)
    ],
    sha256 = hash,
)

build_appliance(
    name = "build-appliance.prebuilt",
    src = ":build-appliance.tar.zst",
    visibility = [
        "antlir//antlir/antlir2/flavor:none",
    ]
)

image.layer(
    name = "build-appliance",
    build_appliance = ":build-appliance.prebuilt",
    features = [
        "//antlir/antlir2/build_appliance:features",
    ],
    dnf_available_repos = "//antlir/antlir2/package_managers/dnf/build_appliance:empty-dnf-reposet",
    dnf_versionlock = "//antlir/antlir2/package_managers/dnf/build_appliance:empty-dnf-versionlock.json",
    dnf_excluded_rpms = [],
)
