load(":defs.bzl", "fake_macro_library")
load(":oss_shim.bzl", "get_visibility")

# IMPORTANT: If you add new `.bzl` files or dependencies in `fs_image/`,
# make sure their dependency structure is reflected below.  Just run `grep
# 'load(":'` from `fs_image/`, and visually compare with the below.  Future:
# this could easily be automated in the style of Bistro's
# `targets_to_cmake_lists.py`.

# The following rules are "fake" in the sense that their build artifacts are
# actually discarded.  However, they are required to trigger automatic
# builds and tests on changes to .bzl files, so it is important to keep
# these up-to-date.  Furthermore, when you add a new rule type, you'll need
# to make its targets depend on the corresponding `fake_macro_library`.
# This should eventually become unnecessary, follow Q10141.

fake_macro_library(
    name = "artifacts_require_repo",
    srcs = ["artifacts_require_repo.bzl"],
)

fake_macro_library(
    name = "sha256",
    srcs = ["sha256.bzl"],
)

fake_macro_library(
    name = "layer_resource",
    srcs = ["layer_resource.bzl"],
)

fake_macro_library(
    name = "target_helpers",
    srcs = ["target_helpers.bzl"],
    deps = [":sha256"],
)

fake_macro_library(
    name = "image_source",
    srcs = ["image_source.bzl"],
    deps = [":maybe_export_file"],
)

fake_macro_library(
    name = "image_layer_utils",
    srcs = ["image_layer_utils.bzl"],
)

fake_macro_library(
    name = "image_utils",
    srcs = ["image_utils.bzl"],
)

fake_macro_library(
    name = "add_stat_options",
    srcs = ["add_stat_options.bzl"],
)

fake_macro_library(
    name = "maybe_export_file",
    srcs = ["maybe_export_file.bzl"],
)

fake_macro_library(
    name = "target_tagger",
    srcs = ["target_tagger.bzl"],
    deps = [
        ":image_source",
        ":target_helpers",
        ":wrap_runtime_deps",
    ],
)

fake_macro_library(
    name = "rpm_repo_snapshot",
    srcs = ["rpm_repo_snapshot.bzl"],
    deps = [
        ":maybe_export_file",
        ":target_helpers",
        ":wrap_runtime_deps",
    ],
)

fake_macro_library(
    name = "wrap_runtime_deps",
    srcs = ["wrap_runtime_deps.bzl"],
    deps = [
        ":artifacts_require_repo",
        ":target_helpers",
    ],
)

fake_macro_library(
    name = "image_layer",
    srcs = [
        "compile_image_features.bzl",
        "image_layer.bzl",
    ],
    deps = [
        ":artifacts_require_repo",
        ":image_utils",
        ":target_tagger",
        "//fs_image/bzl/image_actions:install",
        "//fs_image/bzl/image_actions:mkdir",
        "//fs_image/bzl/image_actions:tarball",
    ],
)

fake_macro_library(
    name = "image_layer_alias",
    srcs = ["image_layer_alias.bzl"],
    deps = [],
)

fake_macro_library(
    name = "fetched_package_layer",
    srcs = ["fetched_package_layer.bzl"],
    deps = [
        ":image_layer",
        ":target_helpers",
        "//fs_image/bzl/image_actions:feature",
    ],
)

fake_macro_library(
    name = "image_package",
    srcs = ["image_package.bzl"],
    deps = [":image_utils"],
)

fake_macro_library(
    name = "image_unittest_helpers",
    srcs = ["image_unittest_helpers.bzl"],
    deps = [
        ":image_layer",
        "//fs_image/bzl/image_actions:install",
    ],
)

fake_macro_library(
    name = "image_python_unittest",
    srcs = ["image_python_unittest.bzl"],
    deps = [":image_unittest_helpers"],
)

fake_macro_library(
    name = "image_cpp_unittest",
    srcs = ["image_cpp_unittest.bzl"],
    deps = [":image_unittest_helpers"],
)

fake_macro_library(
    name = "shape",
    srcs = ["shape.bzl"],
)
