load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/genrule_in_image:genrule_in_image.bzl", "genrule_in_image")
load("//antlir/antlir2/testing:image_rpms_test.bzl", "image_test_rpm_names")
load("//antlir/bzl:build_defs.bzl", "internal_external")

oncall("antlir")

image.layer(
    name = "example",
    default_os = "centos9",
    features = [
        feature.rpms_install(rpms = [
            "basesystem",
            "bash",
            "util-linux",
            "rpm",
        ]),
        feature.install_text(
            dst = "/hello",
            text = "I am antlir\n",
        ),
    ],
)

image.layer(
    name = "child-that-installs-rpms",
    features = [
        feature.rpms_install(rpms = ["systemd"]),
    ],
    parent_layer = ":example",
)

image_test_rpm_names(
    name = "test-rpms-installed",
    src = "rpms.txt",
    compatible_with = ["ovr_config//cpu:x86_64"],
    labels = internal_external(
        fb = [],
        oss = ["disabled"],
    ),
    layer = ":child-that-installs-rpms",
    rootless = True,
)

genrule_in_image(
    name = "genrule_in_image",
    out = "uname.txt",
    bash = """
        uname -r > $OUT
    """,
    layer = ":example",
)
