load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_rpms_test.bzl", "image_test_rpm_names")
load("//antlir/bzl:build_defs.bzl", "internal_external")

oncall("antlir")

image.layer(
    name = "example",
    default_os = "centos9",
    features = [
        feature.rpms_install(rpms = [
            "basesystem",
            "bash",
            "util-linux",
            "rpm",
        ]),
        feature.install_text(
            dst = "/hello",
            text = "I am antlir\n",
        ),
    ],
    target_compatible_with = [
        # TODO(T156455885): RE builds for ARM must be scheduled on an ARM
        # worker, but it's not clear if that's possible.
        "ovr_config//cpu:x86_64",
    ],
)

image.layer(
    name = "child-that-installs-rpms",
    features = [
        feature.rpms_install(rpms = ["systemd"]),
    ],
    parent_layer = ":example",
)

image_test_rpm_names(
    name = "test-rpms-installed",
    src = "rpms.txt",
    labels = internal_external(
        fb = [],
        oss = ["disabled"],
    ),
    layer = ":child-that-installs-rpms",
    rootless = True,
)
