load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/bzl:systemd.bzl", "systemd")

oncall("antlir")

# Install the necessary configuration to notify the `antlir.vm` runtime when a
# host has booted.
feature.new(
    name = "notify",
    features = [
        systemd.install_unit(
            "virtio-notify@.service",
            use_antlir2 = True,
        ),
        # Enable using the virtio socket named "notify-host"
        systemd.enable_unit(
            "virtio-notify@notify-host.service",
            use_antlir2 = True,
        ),
    ],
    visibility = ["PUBLIC"],
)
