load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("twimage")

rust_library(
    name = "antlir2_compile",
    srcs = glob([
        "src/**/*.rs",
        # @oss-disable
    ]),
    deps = [
        "anyhow",
        "libloading",
        "serde",
        "thiserror",
        "tracing",
        "xattr",
        "//antlir/antlir2/antlir2_features:antlir2_features",
        "//antlir/antlir2/antlir2_users:antlir2_users",
        "//antlir/buck/buck_label:buck_label",
    ],
)
