load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir2_compile",
    srcs = glob([
        "src/**/*.rs",
        # @oss-disable[end= ]: "src/facebook/chef_solo/*",
    ]),
    deps = [
        "anyhow",
        "cap-std",
        "libloading",
        "nix",
        "openat2",
        "serde",
        "serde_json",
        "static_assertions",
        "thiserror",
        "tracing",
        "xattr",
        "//antlir/antlir2/antlir2_features:antlir2_features",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/antlir2/antlir2_users:antlir2_users",
        "//antlir/buck2/buck_label:buck_label",
    ],
)
