# @noautodeps

load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "generator_lib",
    srcs = ["src/generator_lib.rs"],
    test_deps = [
        "maplit",
        "slog_glog_fmt",
    ],
    deps = [
        "anyhow",
        "serde",
        "serde_json",
        "slog",
        "//metalos/lib/systemd:systemd",
    ],
)
