load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

image.layer(
    name = "base",
    features = [
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "ensure_dirs_exist",
    features = [
        feature.ensure_dirs_exist(dirs = "/a"),
        feature.ensure_dirs_exist(dirs = "/foo/bar"),
        feature.ensure_subdirs_exist(
            into_dir = "/foo/bar",
            subdirs_to_create = "baz/qux",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "ensure-dirs_exist-test",
    diff = "ensure_dirs_exist.toml",
    layer = ":ensure_dirs_exist",
)
