[a]
op = 'added'

[a.diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "root"
group = "root"
content_hash = "0"

[foo]
op = 'added'

[foo.diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "root"
group = "root"
content_hash = "0"

["foo/bar"]
op = 'added'

["foo/bar".diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "root"
group = "root"
content_hash = "0"

["foo/bar/baz"]
op = 'added'

["foo/bar/baz".diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "root"
group = "root"
content_hash = "0"

["foo/bar/baz/qux"]
op = 'added'

["foo/bar/baz/qux".diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "root"
group = "root"
content_hash = "0"
