# @oss-disable[end= ]: load("@fbsource//tools/target_determinator/macros:ci.bzl", "ci")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_test.bzl", "image_rust_test")
load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "isolate_unshare",
    srcs = glob(["src/**/*.rs"]),
    compatible_with = [
        "ovr_config//os:linux",
    ],
    resources = {
        "preexec": "//antlir/antlir2/antlir2_isolate/isolate_unshare/isolate_unshare_preexec:isolate_unshare_preexec",
    },
    visibility = ["//antlir/antlir2/antlir2_isolate:"],
    deps = [
        "buck-resources",
        "nix",
        "serde_json",
        "thiserror",
        "//antlir/antlir2/antlir2_isolate/isolate_cfg:isolate_cfg",
    ],
)

image.layer(
    name = "isolated-root",
    features = [
        feature.rpms_install(rpms = [
            "coreutils",
            "bash",
        ]),
        feature.install_text(
            dst = "/foo",
            text = "foo\n",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/bar",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/baz",
        ),
        feature.ensure_dirs_exist(dirs = "/input"),
    ],
)

image.layer(
    name = "test-layer",
    features = [
        feature.rpms_install(rpms = ["basesystem"]),
        feature.layer_mount(
            mountpoint = "/isolated",
            source = ":isolated-root",
        ),
        feature.install_text(
            dst = "/bar",
            text = "bar\n",
        ),
        feature.install_text(
            dst = "/baz",
            text = "baz\n",
        ),
    ],
)

image_rust_test(
    name = "tests",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/tests.rs",
    # This test does not work under architecture emulation. Mark it as such in
    # buck-land, and also disable scheduling CI for aarch64
    exec_compatible_with = select({
        "ovr_config//cpu:arm64": ["ovr_config//cpu:arm64"],
        "ovr_config//cpu:x86_64": ["ovr_config//cpu:x86_64"],
    }),
    # @oss-disable[end= ]: labels = ci.labels(ci.remove(ci.aarch64())),
    layer = ":test-layer",
    # execute the test with isolate_unshare not systemd-nspawn
    rootless = True,
    deps = [
        "nix",
        "tempfile",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
    ],
)
