load("//antlir/bzl:shape.bzl", "shape")
load("//metalos:defs.bzl", "rust_binary")

shape.impl(
    name = "service.shape",
    deps = ["//antlir/bzl:target.shape"],
)

rust_binary(
    name = "serialize-shape",
    srcs = ["serialize_shape.rs"],
    unittests = False,
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "fbthrift",
        "serde_json",
        ":service.shape-rust",
    ],
)
