# @noautodeps

load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "image",
    srcs = glob(["src/*.rs"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "anyhow",
        "async-trait",
        "bytes",
        "futures",
        "reqwest",
        "slog",
        "thiserror",
        "tokio",
        "//metalos/host_configs:api-rust",
        "//metalos/lib/btrfs:btrfs",
        "//metalos/lib/metalos_paths:metalos_paths",
    ],
)
