# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""
Rule that stamps a .note.dlopen section onto a binary using objcopy.
The note payload is generated by dlopen_notes.rs containing 5 entries
with different priorities and features.

This uses the same objcopy target that antlir uses for debuginfo splitting:
  fbcode//third-party/binutils:objcopy  (fb)
  toolchains//:objcopy                  (oss)
"""

load("//antlir/buck2/bzl:ensure_single_output.bzl", "ensure_single_output")
load("//antlir/bzl:internal_external.bzl", "internal_external")

def _add_dlopen_note_impl(ctx: AnalysisContext) -> list[Provider]:
    src = ensure_single_output(ctx.attrs.src)
    out = ctx.actions.declare_output(ctx.attrs.out)

    # notes is dict of section_name -> list of entries, e.g.
    # {".note.dlopen": [entry1, entry2], ".note.foobar": [entry3]}
    # The dict is serialized to a JSON string via json.encode and passed to the
    # generator binary using antlir's Json CLI flag type (json_arg::Json).
    ctx.actions.run(
        cmd_args(
            ctx.attrs._generator[RunInfo],
            "add",
            cmd_args(json.encode(ctx.attrs.notes), format = "--notes={}"),
            cmd_args(src, format = "--src={}"),
            cmd_args(out.as_output(), format = "--out={}"),
            cmd_args(ctx.attrs.objcopy[RunInfo], format = "--objcopy={}"),
        ),
        category = "add_dlopen_note",
    )

    return [
        DefaultInfo(
            default_output = out,
        ),
        RunInfo(
            args = cmd_args(out),
        ),
    ]

# Value can be string or list of strings (e.g. soname: ["libz.so.1"])
_notes_value = attrs.one_of(
    attrs.string(),
    attrs.list(attrs.string()),
)

# Single entry dict: keys are strings, values are _notes_value
_notes_entry = attrs.dict(
    key = attrs.string(),
    value = _notes_value,
)

add_dlopen_note = rule(
    impl = _add_dlopen_note_impl,
    attrs = {
        "notes": attrs.dict(
            key = attrs.string(),
            value = attrs.list(_notes_entry),
            default = {},
            doc = "Dict of section_name -> list of dlopen entries. Key is section name like '.note.dlopen' or '.note.foobar' (configurable to test matching on note type not name). Value is list of entries (dicts with feature, priority, soname, description). Allows testing repeated sections and multiple entries per section via single file.",
        ),
        "objcopy": attrs.exec_dep(
            default = internal_external(
                fb = "fbsource//third-party/binutils:objcopy",
                oss = "toolchains//:objcopy",
            ),
        ),
        "out": attrs.string(default = "dlopen_binary"),
        "src": attrs.dep(),
        "_generator": attrs.exec_dep(
            default = "fbcode//antlir/antlir2/features/extract/tests/dlopen:dlopen-notes",
        ),
    },
)
