load("//antlir/bzl:build_defs.bzl", "buck_genrule", "python_library", "python_unittest")

oncall("twimage")

python_library(
    name = "http_socket_server",
    srcs = ["http_socket_server.py"],
)

python_unittest(
    name = "test-http-socket-server",
    srcs = ["tests/test_http_socket_server.py"],
    needed_coverage = [
        (100, ":http_socket_server"),
    ],
    deps = [":http_socket_server"],
)

python_library(
    name = "server_start_wrapper",
    srcs = ["server_start_wrapper.py"],
)

python_library(
    name = "proxy_url",
    srcs = ["proxy_url.py"],
    deps = [
        "//antlir:common",
    ],
)

buck_genrule(
    name = "test-cert",
    bash = """\
set -ue -o pipefail -o noclobber

mkdir "$OUT"
openssl req -new -x509 -keyout "$OUT"/localhost.pem -out "$OUT"/localhost.pem -days 365 -nodes \
-subj "/C=US/ST=YourState/L=YourCity/O=Example-Certificates/CN=localhost"
""",
)

python_unittest(
    name = "test-proxy-url",
    srcs = ["tests/test_proxy_url.py"],
    needed_coverage = [
        (100, ":proxy_url"),
    ],
    resources = {
        ":test-cert": "tests/test-cert",
    },
    deps = [
        ":proxy_url",
    ],
)
