[tar]
op = "added"

[tar.diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar/foo"]
op = "added"

["tar/foo".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar/foo/bar"]
op = "added"

["tar/foo/bar".diff]
mode = "u+rw,g+r,o+r"
file-type = "regular-file"
user = "root"
group = "root"
text = """
I am bar
"""

["tar/foo/baz"]
op = "added"

["tar/foo/baz".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar/foo/baz/qux"]
op = "added"

["tar/foo/baz/qux".diff]
mode = "u+rw,g+r,o+r"
file-type = "regular-file"
user = "root"
group = "root"
text = """
I am qux
"""

["tar.gz"]
op = "added"

["tar.gz".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar.gz/foo"]
op = "added"

["tar.gz/foo".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar.gz/foo/bar"]
op = "added"

["tar.gz/foo/bar".diff]
mode = "u+rw,g+r,o+r"
file-type = "regular-file"
user = "root"
group = "root"
text = """
I am bar
"""

["tar.gz/foo/baz"]
op = "added"

["tar.gz/foo/baz".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar.gz/foo/baz/qux"]
op = "added"

["tar.gz/foo/baz/qux".diff]
mode = "u+rw,g+r,o+r"
file-type = "regular-file"
user = "root"
group = "root"
text = """
I am qux
"""

["tar.zst"]
op = "added"

["tar.zst".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar.zst/foo"]
op = "added"

["tar.zst/foo".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar.zst/foo/bar"]
op = "added"

["tar.zst/foo/bar".diff]
mode = "u+rw,g+r,o+r"
file-type = "regular-file"
user = "root"
group = "root"
text = """
I am bar
"""

["tar.zst/foo/baz"]
op = "added"

["tar.zst/foo/baz".diff]
mode = "u+rwx,g+rx,o+rx"
file-type = "directory"
user = "root"
group = "root"
content-hash = 0

["tar.zst/foo/baz/qux"]
op = "added"

["tar.zst/foo/baz/qux".diff]
mode = "u+rw,g+r,o+r"
file-type = "regular-file"
user = "root"
group = "root"
text = """
I am qux
"""
