load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "http_test",
    srcs = ["src/http_test.rs"],
    test_deps = [
        "anyhow",
        "maplit",
        "reqwest",
    ],
    unittests = [
        "container",
    ],
    deps = [
        "http",
        "hyper",
        "tokio",
        "url",
    ],
)
