load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "metalos_host_configs",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "strum_macros",
        "url",
        "uuid",
        "//metalos/host_configs:api-rust",
        # @oss-disable: "//metalos/host_configs/facebook:host-facebook-rust", 
        # @oss-disable: "//metalos/host_configs/facebook/proxy/if:deployment_specific-rust", 
        # @oss-disable: "//metalos/host_configs/facebook/proxy/if/deployments:legacy_deployment-rust", 
        # @oss-disable: "//metalos/host_configs/facebook/proxy/if/deployments:metalos_deployment-rust", 
        # @oss-disable: "//metalos/host_configs/facebook/proxy/if/deployments:netos_deployment-rust", 
        "//metalos/lib/metalos_paths:metalos_paths",
        "//metalos/lib/thrift_wrapper:thrift_wrapper",
    ],
)
