load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

rust_library(
    name = "fallback_identity_checker",
    srcs = ["src/lib.rs"],
    test_deps = [
        "fbsource//third-party/rust:mockall",
        "fbsource//third-party/rust:tempfile",
        "//common/rust/shed/fbinit:fbinit",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:slog",
        "fbsource//third-party/rust:thiserror",
        "//common/rust/identity:identity",
        "//common/rust/logging:logging",
        "//metalos/metald/src/lib/permission_checker:permission_checker",
    ],
)
