load("//antlir/bzl:build_defs.bzl", "rust_binary", "rust_library")

rust_library(
    name = "antlir2_isolate",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "nix",
        "uuid",
    ],
)

rust_binary(
    name = "cli",
    srcs = ["main.rs"],
    unittests = False,
    deps = [
        "anyhow",
        "clap",
        ":antlir2_isolate",
    ],
)
