[package]
edition = "2018"
name = "combine"
version = "0.0.1"

[[bin]]
name = "combine"
path = "src/combine.rs"

[dependencies]
anyhow = "1.0.38"
quote = "1.0.9"
rustfmt = "0.10.0"
syn = {version = "1.0.64", features = ["full", "visit-mut"]}
