# @oss-disable[end= ]: load("@fbsource//tools/build_defs:fbsource_utils.bzl", "is_arvr_mode")
load("//antlir/bzl:build_defs.bzl", "alias", "rust_bindgen_library", "rust_library")
load("//antlir/bzl:internal_external.bzl", "internal_external")

oncall("antlir")

# We can't actually select on arvr modes because of exec platform shenanigans,
# so we have to create this alias that lets us make things unavailable under
# arvr modes.
# https://fb.workplace.com/groups/asktp/posts/3317571605206390
alias(
    name = "available",
    # @oss-disable[end= ]: actual = "ovr_config//os:linux" if not is_arvr_mode() else "ovr_config//:none",
    actual = "ovr_config//os:linux", # @oss-enable
    visibility = ["//antlir/..."],
)

rust_bindgen_library(
    name = "libcap-sys",
    compatible_with = [":available"],
    cpp_deps = [
        internal_external(
            fb = "third-party//libcap:cap",
            oss = "//third-party/cxx/system:libcap",
        ),
    ],
    generate = ("types", "functions", "vars"),
    header = "bridge.h",
    visibility = [],
)

rust_library(
    name = "libcap",
    srcs = glob(["src/*.rs"]),
    compatible_with = [":available"],
    deps = [
        "libc",
        ":libcap-sys",
    ],
)
