load("//antlir/bzl:constants.bzl", "REPO_CFG")
load("//antlir/bzl:flavor_helpers.bzl", "flavor_helpers")
load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl/image/feature:defs.bzl", "feature")

# The base image.layer for a systemd boot partition
# There is no kernel, initrd, or loader entries
# configured in this layer.
image.layer(
    name = "base",
    features = [
        feature.ensure_subdirs_exist("/", "EFI"),
        feature.ensure_subdirs_exist("/EFI", "BOOT"),
        feature.ensure_subdirs_exist("/EFI", "Linux"),
        feature.ensure_subdirs_exist("/EFI", "systemd"),
        feature.ensure_subdirs_exist("/", "loader"),
        feature.ensure_subdirs_exist("/loader", "entries"),
        feature.clone(
            REPO_CFG.artifact["metalos.layer.base"],
            "/usr/lib/systemd/boot/efi/systemd-bootx64.efi",
            "/EFI/systemd/systemd-bootx64.efi",
        ),
        feature.clone(
            REPO_CFG.artifact["metalos.layer.base"],
            "/usr/lib/systemd/boot/efi/systemd-bootx64.efi",
            "/EFI/BOOT/BOOTX64.efi",
        ),
    ],
    flavor = flavor_helpers.get_antlir_linux_flavor(),
    visibility = ["PUBLIC"],
)
