load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_demo_toolchains()

# TODO: get this from the cxx toolchain
sh_binary(
    name = "objcopy",
    main = "objcopy",
    visibility = ["PUBLIC"],
)
