load("//antlir/antlir2/features:defs.bzl", "feature_impl")

oncall("antlir")

feature_impl(
    name = "group",
    deps = [
        "anyhow",
        "//antlir/antlir2/antlir2_users:antlir2_users",
    ],
)
