load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "image-diff-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "base64",
        "clap",
        "hex",
        "md-5",
        "serde",
        "serde_with",
        "similar",
        "toml",
        "walkdir",
        "xattr",
        "//antlir/antlir2/antlir2_mode:antlir2_mode",
        "//antlir/antlir2/antlir2_rootless:antlir2_rootless",
        "//antlir/antlir2/antlir2_users:antlir2_users",
        "//antlir/antlir2/testing/image_test_lib:image_test_lib",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
