# @noautodeps

load("//antlir/bzl:oss_shim.bzl", "python_unittest")

python_unittest(
    name = "test-fs_utils",
    srcs = ["test_fs_utils.py"],
    deps = [
        "//antlir:fs_utils",
        "//antlir/rust:rust",
    ],
)
