load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "antlir2-receive",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "jwalk",
        # @oss-disable[end= ]: "serde",
        # @oss-disable[end= ]: "serde_json",
        "tar",
        "tempfile",
        "thiserror",
        "tracing",
        "tracing-glog",
        "tracing-subscriber",
        "//antlir/antlir2/antlir2_btrfs:antlir2_btrfs",
        "//antlir/antlir2/antlir2_error_handler:antlir2_error_handler",
        "//antlir/antlir2/antlir2_facts:antlir2_facts",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/antlir2/antlir2_rootless:antlir2_rootless",
        "//antlir/antlir2/antlir2_working_volume:antlir2_working_volume",
    ],
)
