load("//antlir/antlir2/antlir2_vm/bzl:defs.bzl", "vm")
load("//antlir/bzl:build_defs.bzl", "rust_binary")
load("//metalos/vm/disks:simple.bzl", "simple_disk")

# Verify different type of tests
vm.cpp_test(
    name = "cpp-test",
    srcs = ["test.cpp"],
    env = {
        "ANTLIR2_TEST": "1",
        "ENV_ARTIFACT": "$(exe :sidecar)",
    },
    run_as_bundle = True,
    vm_host = vm.artifacts.default_vms.initrd_boot,
)

vm.python_test(
    name = "python-test",
    srcs = ["test.py"],
    env = {
        "ANTLIR2_TEST": "1",
        "ENV_ARTIFACT": "$(exe :sidecar)",
    },
    run_as_bundle = True,
    vm_host = vm.artifacts.default_vms.initrd_boot,
)

vm.rust_test(
    name = "rust-test",
    srcs = ["test.rs"],
    crate = "test_rs",
    crate_root = "test.rs",
    env = {
        "ANTLIR2_TEST": "1",
        "ENV_ARTIFACT": "$(exe :sidecar)",
    },
    run_as_bundle = True,
    vm_host = vm.artifacts.default_vms.initrd_boot,
)

vm.sh_test(
    name = "sh-test",
    env = {
        "ANTLIR2_TEST": "1",
        "ENV_ARTIFACT": "$(exe :sidecar)",
    },
    test = "test.sh",
    vm_host = vm.artifacts.default_vms.initrd_boot,
)

# Verify all pre-configured VMs
[
    vm.rust_test(
        name = "test-" + name,
        srcs = ["test.rs"],
        crate = "test_rs",
        crate_root = "test.rs",
        env = {
            "ANTLIR2_TEST": "1",
            "ENV_ARTIFACT": "$(exe :sidecar)",
        },
        vm_host = target,
    )
    for name, target in {
        "disk-boot": vm.artifacts.default_vms.disk_boot,
        "initrd-boot": vm.artifacts.default_vms.initrd_boot,
        "nvme-disk-boot": vm.artifacts.default_vms.nvme_disk_boot,
    }.items()
]

# Test for sidecar
rust_binary(
    name = "sidecar",
    srcs = ["sidecar.rs"],
    crate_root = "sidecar.rs",
    deps = [
        "anyhow",
        "clap",
        "tokio",
        "warp",
    ],
)

vm.host(
    name = "vm-with-sidecar",
    compatible_with = ["ovr_config//cpu:x86_64"],
    disks = [simple_disk.default_boot_disk],
    sidecar_services = [
        "$(exe :sidecar)",
        "$(exe :sidecar) --port 8001",
    ],
)

vm.rust_test(
    name = "test-sidecar",
    srcs = ["test_sidecar.rs"],
    crate = "test_sidecar",
    crate_root = "test_sidecar.rs",
    vm_host = ":vm-with-sidecar",
    deps = [
        "reqwest",
        "tokio",
        ":sidecar",
    ],
)

# Test for TPM
vm.host(
    name = "vm-with-tpm",
    compatible_with = ["ovr_config//cpu:x86_64"],
    disks = [simple_disk.default_boot_disk],
    use_tpm = True,
)

vm.rust_test(
    name = "test-tpm",
    srcs = ["tpm.rs"],
    crate = "tpm",
    crate_root = "tpm.rs",
    vm_host = ":vm-with-tpm",
)

# Example target for running a command
vm.run_command(
    name = "run-command",
    command = "uname -r",
    vm_host = vm.artifacts.default_vms.initrd_boot,
)

vm.run_command(
    name = "run-command-with-location",
    command = "bash -c 'echo $(location :sidecar)'",
    vm_host = vm.artifacts.default_vms.initrd_boot,
)
