load("//antlir/bzl:oss_shim.bzl", "export_file")

oncall("twimage")

# This is the client ssh key used to connect to the virtual machine with SSH
export_file(
    name = "privkey",
    src = "id_ecdsa",
)

# And the corresponding public key that is installed into the default image
export_file(
    name = "pubkey",
    src = "id_ecdsa.pub",
    visibility = ["PUBLIC"],
)

export_file(
    name = "sshd-hostkey.conf",
)

export_file(
    name = "sshd-keygen.service",
)

export_file(
    name = "sshd.tmpfiles.conf",
)
