#!/bin/bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

input="$2"
output="$3"

XAR_ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

script='
mount --make-rprivate /
exec chroot '"$XAR_ROOT"' /usr/bin/rpm2extents SHA256 2>/dev/null
'

exec unshare -mUr /bin/bash -ue -c "$script" < "$input" > "$output"
