# @generated
load("@antlir//antlir/antlir2/package_managers/dnf/rules:repo.bzl", "repo_set")

repo_set(name='repos',
         repos=['//snapshot/rpm/centos10/centos-stream/10-stream/AppStream/x86_64/os:centos-stream_10-stream_AppStream_x86_64_os',
                '//snapshot/rpm/centos10/centos-stream/10-stream/BaseOS/x86_64/os:centos-stream_10-stream_BaseOS_x86_64_os',
                '//snapshot/rpm/centos10/centos-stream/10-stream/CRB/x86_64/os:centos-stream_10-stream_CRB_x86_64_os',
                '//snapshot/rpm/centos10/centos-stream/SIGs/10-stream/hyperscale/x86_64/packages-main:centos-stream_SIGs_10-stream_hyperscale_x86_64_packages-main',
                '//snapshot/rpm/centos10/centos-stream/SIGs/10-stream/hyperscale/x86_64/packages-experimental:centos-stream_SIGs_10-stream_hyperscale_x86_64_packages-experimental',
                '//snapshot/rpm/centos10/centos-stream/SIGs/10-stream/hyperscale/x86_64/packages-facebook:centos-stream_SIGs_10-stream_hyperscale_x86_64_packages-facebook',
                '//snapshot/rpm/centos10/fedora/epel/10/Everything/x86_64:fedora_epel_10_Everything_x86_64'],
         visibility=['PUBLIC'])
