load("//antlir/bzl:oss_shim.bzl", "export_file")
load("//antlir/bzl:systemd.bzl", "systemd")
load("//antlir/bzl/image/feature:defs.bzl", "feature")
load("//metalos:defs.bzl", "rust_binary", "rust_library")
load("//metalos/bzl/service:service.bzl", "native_service")
load("//metalos/bzl/service:service.shape.bzl", "cmd_t", "dependency_t", "exec_t", "restart_settings_t", "service_t")
# @oss-disable: load("//metalos/metald/src/facebook:deps.bzl", "deps", "test_deps") 

rust_library(
    name = "metald_lib",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/metald.rs",
    named_deps = {
        "plain_systemd": "systemd",
    },
    test_deps = test_deps,
    deps = [
        "anyhow",
        "async-trait",
        "clap",
        "slog",
        "slog_glog_fmt",
        "thiserror",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/srserver:srserver",
        "//metalos/host_configs/lifecycle:lifecycle",
        "//metalos/host_configs/rust:metalos_host_configs",
        "//metalos/host_configs:Metalctl-metadata-sys",
        "//metalos/host_configs:api-rust",
        "//metalos/lib/kexec:metalos_kexec",
        "//metalos/lib/package_download:package_download",
        "//metalos/lib/service:service",
        "//metalos/lib/state:state",
        "//metalos/lib/systemd:systemd",
    ] + (
        # @oss-disable: deps 
        # @oss-enable []
    ),
)

rust_binary(
    name = "metald",
    srcs = ["main.rs"],
    crate_root = "main.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        ":metald_lib",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/fbinit:fbinit-tokio",
    ],
)

install_allowed_identities = [
    feature.ensure_subdirs_exist(
        "/usr/lib/",
        "metald/metald_allowed_identities",
    ),
    feature.install(
        "src/facebook/metald_allowed_identities",
        "/usr/lib/metald/metald_allowed_identities/default",
        mode = 0o644,
    ),
]

feature.new(
    name = "features",
    features = [
        # metald.service still needed as placeholder to allow metald.socket to activate.
        # The native_service version will take precedence.
        systemd.install_unit("metalos.metald.service"),
        systemd.install_unit("metalos.metald.socket"),
        systemd.enable_unit("metalos.metald.socket"),
        feature.install_buck_runnable(
            ":metald",
            "/usr/lib/metalos/metald",
        ),
        systemd.install_dropin("bindmount.conf", "metalos.metald.service"),
    ] + install_allowed_identities,
    visibility = ["//metalos/os/..."],
)

native_service(
    extra_features = install_allowed_identities,
    service = service_t(
        name = "metalos.metald",
        dependencies = [
            dependency_t(
                mode = "after-only",
                unit = "network-online.target",
            ),
            dependency_t(
                mode = "after-only",
                unit = "metalos.metald.socket",
            ),
        ],
        exec_info = exec_t(
            restart = restart_settings_t(
                mode = "always",
            ),
            run = [
                cmd_t(
                    args = [
                        "--systemd-socket",
                    ],
                    binary = "//metalos/metald:metald",
                ),
            ],
            service_type = "simple",
        ),
    ),
    visibility = ["//metalos/os/..."],
)

export_file(name = "src/facebook/metald_allowed_identities")

export_file(name = "metalos.metald.service")
