load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "run",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "tracing",
        "tracing-subscriber",
        "//antlir:find_root",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/filesystem/absolute_path:absolute_path",
    ],
)
