[[buildscript]]
[buildscript.gen_srcs]
files = ["op.rs", "consts.rs"]

[env]
# [sic] - the buildscript swaps this, but it doesn't really matter
TYPENUM_BUILD_CONSTS = "op.rs"
TYPENUM_BUILD_OP = "consts.rs"
