load("//antlir/antlir2/bzl:hoist.bzl", "hoist")
load("//antlir/antlir2/bzl:platform.bzl", "arch_select")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/bzl:build_defs.bzl", "python_unittest")

oncall("antlir")

image.layer(
    name = "parent",
    features = [
        feature.ensure_dirs_exist(dirs = "/arch"),
        feature.install_text(
            dst = "/arch/parent",
            text = arch_select(
                aarch64 = "aarch64",
                x86_64 = "x86_64",
            ),
        ),
    ],
)

image.layer(
    name = "child.x86_64",
    features = [
        feature.ensure_dirs_exist(dirs = "/arch"),
        feature.install_text(
            dst = "/arch/child",
            text = arch_select(
                aarch64 = "aarch64",
                x86_64 = "x86_64",
            ),
        ),
    ],
    parent_layer = ":parent",
    target_arch = "x86_64",
)

image.layer(
    name = "child.aarch64",
    features = [
        feature.ensure_dirs_exist(dirs = "/arch"),
        feature.install_text(
            dst = "/arch/child",
            text = arch_select(
                aarch64 = "aarch64",
                x86_64 = "x86_64",
            ),
        ),
    ],
    parent_layer = ":parent",
    target_arch = "aarch64",
)

hoist(
    name = "data.x86_64",
    dir = True,
    layer = ":child.x86_64",
    path = "/arch",
)

hoist(
    name = "data.aarch64",
    dir = True,
    layer = ":child.aarch64",
    path = "/arch",
)

python_unittest(
    name = "test-child.x86_64",
    srcs = ["test.py"],
    env = {
        "ARCH": "x86_64",
        "DATA": "$(location :data.x86_64)",
    },
)

python_unittest(
    name = "test-child.aarch64",
    srcs = ["test.py"],
    env = {
        "ARCH": "aarch64",
        "DATA": "$(location :data.aarch64)",
    },
)
