load("//antlir/antlir2/bzl:platform.bzl", "arch_select")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/bzl:build_defs.bzl", "python_unittest")

oncall("antlir")

image.layer(
    name = "parent",
    features = [
        feature.install_text(
            dst = "/arch.parent",
            text = arch_select(
                aarch64 = "aarch64",
                x86_64 = "x86_64",
            ),
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "child.x86_64",
    features = [
        feature.install_text(
            dst = "/arch.child",
            text = arch_select(
                aarch64 = "aarch64",
                x86_64 = "x86_64",
            ),
        ),
    ],
    parent_layer = ":parent",
    target_arch = "x86_64",
)

image.layer(
    name = "child.aarch64",
    features = [
        feature.install_text(
            dst = "/arch.child",
            text = arch_select(
                aarch64 = "aarch64",
                x86_64 = "x86_64",
            ),
        ),
    ],
    parent_layer = ":parent",
    target_arch = "aarch64",
)

python_unittest(
    name = "test-child.x86_64",
    srcs = ["test.py"],
    env = {
        "ARCH": "x86_64",
        "LAYER": "$(location :child.x86_64)",
    },
)

python_unittest(
    name = "test-child.aarch64",
    srcs = ["test.py"],
    env = {
        "ARCH": "aarch64",
        "LAYER": "$(location :child.aarch64)",
    },
)
