load("//metalos:defs.bzl", "rust_binary")

rust_binary(
    name = "metalctl-dev",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "clap",
        "fbthrift",
        "nix",
        "slog",
        "slog_glog_fmt",
        "uuid",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/fbinit:fbinit-tokio",
        "//metalos/host_configs/lifecycle:lifecycle",
        "//metalos/host_configs/rust:metalos_host_configs",
        "//metalos/lib/package_download:package_download",
        "//metalos/lib/service:service",
        "//metalos/lib/state:state",
        "//metalos/lib/systemd:systemd",
    ],
)
