load("//metalos:defs.bzl", "rust_binary")

rust_binary(
    name = "metalctl-dev",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "slog",
        "slog_glog_fmt",
        "structopt",
        "tokio",
        "uuid",
        "//metalos/host_configs/rust:metalos_host_configs",
        "//metalos/lib/package_download:package_download",
        "//metalos/lib/service:service",
        "//metalos/lib/systemd:systemd",
    ],
)
