[package]
name = "futures_01_ext"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Extensions for future 0.1 crate"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
bytes-old = { package = "bytes", version = "0.4", features = ["serde"] }
futures = "0.1.31"
tokio-io = "0.1"

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
cloned = { version = "0.1.0", path = "../cloned" }
lock_ext = { version = "0.1.0", path = "../lock_ext" }
maplit = "1.0"
pretty_assertions = "0.6"
quickcheck = "0.9"
tokio = "0.1"
