load("//antlir/bzl:constants.bzl", "REPO_CFG")
load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl:layer_resource.bzl", "layer_resource")
load("//antlir/bzl:oss_shim.bzl", "python_unittest", "rust_binary")
load("//antlir/bzl/foreign/extractor:extract.bzl", "extract")

image.layer(
    name = "extracted",
    features = [
        extract.extract(
            binaries = [
                "/usr/lib/systemd/systemd",
            ],
            buck_binaries = {
                ":repo-built-binary": "/usr/bin/example",
            },
            source = ":source",
        ),
    ],
)

image.layer(
    name = "source",
    parent_layer = REPO_CFG.artifact["extractor.common_deps"],
    features = [
        image.rpms_install(["systemd"]),
    ],
)

rust_binary(
    name = "repo-built-binary",
    srcs = ["repo_built_binary.rs"],
    crate_root = "repo_built_binary.rs",
)

python_unittest(
    name = "test-extracted",
    srcs = ["test_extracted.py"],
    resources = {
        layer_resource(":extracted"): "layer",
        layer_resource(REPO_CFG.build_appliance_default): "source",
    },
    deps = [
        "//antlir:fs_utils",
        "//antlir:testlib_layer_resource",
    ],
)
