load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "starlark-unittest",
    srcs = glob(["src/*.rs"]),
    unittests = False,
    deps = [
        "anyhow",
        "clap-3",
        "hex",
        "regex",
        "sha2",
        "starlark",
    ],
)
