load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("twimage")

rust_binary(
    name = "starlark-unittest",
    srcs = glob(["src/*.rs"]),
    unittests = False,
    deps = [
        "anyhow",
        "clap",
        "gazebo",
        "hex",
        "regex",
        "serde_json",
        "sha2",
        "starlark",
        "//antlir:find_root",
        "//antlir/buck/targets_and_outputs:targets_and_outputs",
        "//antlir/filesystem/absolute_path:absolute_path",
    ],
)
