/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

use std::fmt::Write as FmtWrite;
use std::fs::File;
use std::io::BufWriter;
use std::io::Write;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::Result;
use clap::Parser;
use snapshot_common::Checksums;

/// Regenerate a canonical `repomd.xml` from the on-disk decompressed
/// repodata files.
///
/// The upstream-shipped repomd.xml references compressed `*.gz` paths and
/// carries only sha256 checksums — neither of which works for our snapshot
/// + build pipeline. The build snapshots decompressed `primary.xml` /
/// `filelists.xml` / `other.xml`, and Buck2's `download_file` requires
/// sha1 metadata on outputs that use content-based paths.
///
/// This subcommand produces a repomd.xml that:
///   - References the decompressed filenames (`repodata/primary.xml`, etc.)
///   - Includes both sha1 and sha256 for each `<data>` block (computed
///     from the on-disk file content).
///
/// Conceptually parallel to `metadata generate deb inrelease`.
#[derive(Parser, Debug)]
pub(crate) struct GenerateRepomd {
    #[clap(long)]
    primary_xml: PathBuf,
    #[clap(long)]
    filelists_xml: PathBuf,
    #[clap(long)]
    other_xml: PathBuf,
    /// Output path for the regenerated repomd.xml.
    out: PathBuf,
}

struct Entry {
    typ: &'static str,
    href: &'static str,
    checksums: Checksums,
}

impl GenerateRepomd {
    pub(crate) fn run(self) -> Result<()> {
        let entries = [
            ("primary", "repodata/primary.xml", &self.primary_xml),
            ("filelists", "repodata/filelists.xml", &self.filelists_xml),
            ("other", "repodata/other.xml", &self.other_xml),
        ]
        .into_iter()
        .map(|(typ, href, path)| {
            let file = File::open(path)
                .with_context(|| format!("while opening {}", path.display()))?;
            let checksums = Checksums::from_reader(file)
                .with_context(|| format!("while checksumming {}", path.display()))?;
            Ok::<_, anyhow::Error>(Entry { typ, href, checksums })
        })
        .collect::<Result<Vec<_>>>()?;

        let xml = build_repomd_xml(&entries)?;

        let mut outfile = BufWriter::new(
            stdio_path::create(&self.out)
                .with_context(|| format!("creating {}", self.out.display()))?,
        );
        outfile.write_all(xml.as_bytes())?;
        Ok(())
    }
}

fn build_repomd_xml(entries: &[Entry]) -> Result<String> {
    let mut s = String::new();
    s.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    s.push_str("<!-- @generated by `metadata generate yum repomd` -->\n");
    s.push_str("<repomd xmlns=\"http://linux.duke.edu/metadata/repo\">\n");
    for entry in entries {
        writeln!(s, "  <data type=\"{}\">", entry.typ)?;
        if let Some(hex) = entry.checksums.sha1_hex() {
            writeln!(s, "    <checksum type=\"sha1\">{hex}</checksum>")?;
        }
        if let Some(hex) = entry.checksums.sha256_hex() {
            writeln!(s, "    <checksum type=\"sha256\">{hex}</checksum>")?;
        }
        writeln!(s, "    <location href=\"{}\"/>", entry.href)?;
        writeln!(s, "  </data>")?;
    }
    s.push_str("</repomd>\n");
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_repomd_xml_emits_each_data_block() {
        let entries = vec![
            Entry {
                typ: "primary",
                href: "repodata/primary.xml",
                checksums: Checksums {
                    sha1: Some([0xAA; 20]),
                    sha256: Some([0xBB; 32]),
                },
            },
            Entry {
                typ: "filelists",
                href: "repodata/filelists.xml",
                checksums: Checksums {
                    sha1: Some([0xCC; 20]),
                    sha256: Some([0xDD; 32]),
                },
            },
        ];
        let xml = build_repomd_xml(&entries).expect("build should succeed");
        assert!(xml.contains("type=\"primary\""), "{xml}");
        assert!(xml.contains("type=\"filelists\""), "{xml}");
        // hex encodings of the byte patterns above
        assert!(
            xml.contains(&format!(
                "<checksum type=\"sha1\">{}</checksum>",
                "aa".repeat(20)
            )),
            "{xml}"
        );
        assert!(
            xml.contains(&format!(
                "<checksum type=\"sha256\">{}</checksum>",
                "bb".repeat(32)
            )),
            "{xml}"
        );
        assert!(xml.contains("href=\"repodata/primary.xml\""), "{xml}");
    }
}
