load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "find_root_disk",
    srcs = ["src/find_root_disk.rs"],
    unittests = [
        "vm",
    ],
    deps = [
        "anyhow",
        "udev",
        "//metalos/lib/disk:metalos_disk",
    ],
)
