load("//antlir/bzl:oss_shim.bzl", "rust_binary", "third_party")

rust_binary(
    name = "runner",
    srcs = glob(["src/**/*.rs"]),
    deps = third_party.libraries(
        [
            "anyhow",
            "itertools",
            "mysql_async",
            "rayon",
            "serde",
            "serde_json",
            "structopt",
            "tokio",
        ],
        platform = "rust",
    ),
)
