load("//antlir/bzl:oss_shim.bzl", "rust_binary")

rust_binary(
    name = "runner",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "itertools",
        "rayon",
        "serde",
        "serde_json",
        "structopt",
    ],
)
