# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# @noautodeps

load("//antlir/bzl:build_defs.bzl", "python_binary", "third_party")

oncall("antlir")

python_binary(
    name = "makechunk",
    srcs = ["makechunk.py"],
    main_function = "antlir.antlir2.package_managers.dnf.rules.makechunk.main",
    visibility = ["PUBLIC"],
    deps = third_party.libraries(
        [
            "click",
            "createrepo-c",
        ],
        platform = "pypi",
    ),
)
