load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_test.bzl", "image_rust_test")

oncall("antlir")

image.layer(
    name = "layer",
    features = [
        feature.rpms_install(rpms = ["basesystem"]),
        feature.install_text(
            dst = "/hello.txt",
            text = "Hello world\n",
        ),
        feature.hardlink(
            link = "/aloha.txt",
            target = "/hello.txt",
        ),
    ],
)

image_rust_test(
    name = "test-hardlink",
    srcs = ["test_hardlink.rs"],
    crate_root = "test_hardlink.rs",
    layer = ":layer",
)
