load("//antlir/bzl:constants.bzl", "REPO_CFG")
load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl:layer_resource.bzl", "layer_resource")
load("//antlir/bzl:oss_shim.bzl", "python_unittest")
load("//antlir/bzl/genrule/extractor:extract.bzl", "extract")

image.layer(
    name = "extracted",
    features = [
        extract.extract(
            binaries = [
                "/usr/lib/systemd/systemd",
            ],
            source = REPO_CFG.build_appliance_default,
        ),
    ],
)

python_unittest(
    name = "test-extracted",
    srcs = ["test_extracted.py"],
    resources = {
        layer_resource(":extracted"): "layer",
        layer_resource(REPO_CFG.build_appliance_default): "source",
    },
    deps = [
        "//antlir:fs_utils",
        "//antlir:testlib_layer_resource",
    ],
)
