load("//antlir/bzl:flavor_helpers.bzl", "flavor_helpers")
load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl:layer_resource.bzl", "layer_resource")
load("//antlir/bzl:oss_shim.bzl", "python_unittest", "rust_binary")
load("//antlir/bzl/genrule/extractor:extract.bzl", "extract")
load("//antlir/bzl/image/feature:defs.bzl", "feature")

image.layer(
    name = "deps",
    features = [
        extract.extract(
            binaries = [
                "/usr/lib/systemd/systemd",
                "/usr/bin/repo-built-binary",
            ],
            source = ":source",
        ),
    ],
    flavor = "antlir_test",
    visibility = ["//antlir/bzl/genrule/extractor/tests/..."],
)

image.layer(
    name = "extracted",
    features = [
        extract.extract(
            binaries = [
                "/usr/bin/strace",
            ],
            source = ":source",
        ),
        feature.ensure_dir_symlink("/usr/lib64", "/lib64"),
    ],
    parent_layer = ":deps",
    visibility = ["//antlir/bzl/genrule/extractor/tests/..."],
)

extract.source_layer(
    name = "source",
    features = [
        feature.rpms_install([
            "systemd",
            "strace",
        ]),
        feature.install(
            ":repo-built-binary",
            "/usr/bin/repo-built-binary",
        ),
    ],
    flavor = flavor_helpers.get_antlir_linux_flavor(),
)

rust_binary(
    name = "repo-built-binary",
    srcs = ["repo_built_binary.rs"],
    crate_root = "repo_built_binary.rs",
    link_style = "static",
)

python_unittest(
    name = "test-extracted",
    srcs = ["test_extracted.py"],
    resources = {
        layer_resource(":extracted"): "layer",
        layer_resource(":source"): "source",
    },
    deps = [
        "//antlir:fs_utils",
        "//antlir:testlib_layer_resource",
    ],
)
