load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "absolute_path",
    srcs = ["src/absolute_path.rs"],
    visibility = ["PUBLIC"],
    deps = [
        "ref-cast",
        "serde",
        "thiserror",
    ],
)
