load("//antlir/bzl:oss_shim.bzl", "rust_library", "third_party")

rust_library(
    name = "absolute_path",
    srcs = ["src/absolute_path.rs"],
    deps = third_party.libraries(
        ["thiserror"],
        platform = "rust",
    ),
)
