load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir2_users",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "derive_more",
        "nix",
        "nom",
        "serde",
        "thiserror",
    ],
)
