load("//antlir/bzl:oss_shim.bzl", "buck_filegroup", "export_file")

# The static test keys were generated with the following commands:
#
# export GNUPGHOME=$(mktemp -d)
# cat > "$GNUPGHOME/genkeyparams" <<EOF
#     Key-Type: 1
#     Key-Length: 2048
#     Name-Real: Test Key
#     Name-Email: key@example.com
#     Expire-Date: 0
#     %no-protection
# EOF
# gpg --batch --gen-key --verbose --debug-all "$GNUPGHOME/genkeyparams"
# gpg --output private.key --armor --export-secret-key key@example.com
# gpg --output public.key --armor --export key@example.com
buck_filegroup(
    name = "gpg-test-keypair",
    srcs = [
        "private.key",
        "public.key",
    ],
    # The only other uses of this file are the compiler test images.
    # Let's keep it limited to just that.
    visibility = [
        "//antlir/compiler/test_images/...",
        "//antlir/rpm/...",
    ],
)

export_file(
    name = "gpg-test-signing-key",
    src = "private.key",
    visibility = [
        "//antlir/bzl/genrule/rpmbuild/...",
        "//antlir/rpm:temp_repos",
    ],
)

export_file(
    name = "gpg-test-public-key",
    src = "public.key",
    visibility = ["PUBLIC"],
)
