load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load(":defs.bzl", "image_cxx_toolchain")

oncall("antlir")

image.layer(
    name = "layer",
    features = [
        feature.rpms_install(rpms = [
            "clang",
            "lld",
            "llvm",
        ]),
    ],
)

# This toolchain can build for any antlir2 OS - it just configures 'layer' for
# whatever OS is configured for the leaf node (usually that will just be left
# the default, unless the user uses antlir2_configured_alias)
image_cxx_toolchain(
    name = "toolchain",
    layer = ":layer",
    visibility = ["PUBLIC"],
)
