version: 2.1

jobs:
  smoke-test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          command: ./tools/buck --version
          name: fetch buck
      - run:
          command: ./tools/buck fetch //third-party/...
          name: fetch third-party artifacts
      - run:
          command: ./tools/buck targets //...
          name: evaluate target graph

workflows:
  main:
    jobs:
      - smoke-test
