load("//antlir/bzl:oss_shim.bzl", "export_file")

export_file(name = "10-dm.rules")

export_file(name = "50-udev-default.rules")

export_file(name = "60-block.rules")

export_file(name = "60-persistent-storage.rules")

export_file(name = "75-net-description.rules")

export_file(name = "80-drivers.rules")

export_file(name = "80-net-setup-link.rules")

export_file(name = "95-dm-notify.rules")

export_file(name = "99-systemd.rules")
