# @noautodeps

load("//antlir/bzl:oss_shim.bzl", "export_file")
load(":metalctl.bzl", "metalctl")

# metalctl is split into two binary targets, so that code that requires features
# only found in the rootfs, or larger dependencies can be excluded from the
# initrd.
metalctl(
    name = "metalctl-initrd",
    allocator = "malloc",
    extra_deps = [
        "//metalos/lib/netlink:netlink",
        "//metalos/lib/systemd_generator_lib:systemd_generator_lib",
    ],
    link_style = "static",
    linker_flags = [
        "-Wl,--strip-all",
    ],
    nodefaultlibs = True,
    # some flags to minimize size
    rustc_flags = [
        "-C",
        "opt-level=z",
        "--cfg=initrd",
    ],
)

metalctl(
    name = "metalctl",
)

export_file(
    name = "default-config.toml",
)
