load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "get_host_config",
    srcs = ["src/get_host_config.rs"],
    deps = [
        "anyhow",
        "fbthrift",
        "http",
        "reqwest",
        "url",
        "//metalos/host_configs/rust:metalos_host_configs",
    ],
)
