overlay = "overlay"

[env]
OUT_DIR = "generated"

[[buildscript]]
[buildscript.gen_srcs]
input_srcs = ["src/syntax/grammar.lalrpop"]
files = ["starlark-rust/starlark/src/syntax/grammar.rs"]
[buildscript.gen_srcs.mapped]
"starlark-rust/starlark/src/syntax/grammar.rs" = "generated/grammar.rs"
