load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir2_features",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "libloading",
        "once_cell",
        "serde",
        "serde_json",
        "thiserror",
        "tracing",
        "//antlir/buck/buck_label:buck_label",
    ],
)
