[package]
name = "stats_traits"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Traits for stats crate"
readme = "../../README.md"
homepage = "https://github.com/facebookexperimental/rust-shed/"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
auto_impl = "0.4"
fbinit = { version = "0.1.0", path = "../../fbinit" }
