load("//antlir/bzl:build_defs.bzl", "rust_library")

rust_library(
    name = "dnf_conf",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "configparser",
        "http",
        "itertools",
        "serde",
        "serde_with",
        "url",
    ],
)
