load("//fs_image/bzl:oss_shim.bzl", "python_binary", "python_library", "python_unittest")
load("//fs_image/compiler:defs.bzl", "TEST_IMAGE_PREFIX")

python_library(
    name = "common",
    srcs = ["common.py"],
)

python_library(
    name = "fs_utils",
    srcs = ["fs_utils.py"],
    deps = [":common"],
)

# This helper for the `Path.resource` test exercises our most fragile
# use-case, embedding binaries within binaries.
python_binary(
    name = "test-helper-binary",
    srcs = ["tests/test_helper_binary.py"],
    main_module = "fs_image.tests.test_helper_binary",
)

python_unittest(
    name = "test-fs-utils",
    srcs = [
        "tests/test_fs_utils.py",
        # Added for coverage, redundant with `test-fs-utils-path-resource-*`
        "tests/test_fs_utils_path_resource.py",
    ],
    needed_coverage = [(
        100,
        ":fs_utils",
    )],
    resources = {":test-helper-binary": "tests/helper-binary"},
)

# This is meant to get full functional coverage for `Path.resource`,
# exercising it across all supported `par_style`s.  We cannot do
# `needed_coverage` here, but `test-fs-utils` checks part of the function.
[
    python_unittest(
        name = "test-fs-utils-path-resource-" + style,
        srcs = ["tests/test_fs_utils_path_resource.py"],
        # The "fastzip" test is very important, it is the analog of the
        # open-source PEX format.
        par_style = style,
        resources = {":test-helper-binary": "tests/helper-binary"},
        deps = [":fs_utils"],
    )
    for style in [
        "fastzip",
        "xar",
        "zip",
    ]
]

python_library(
    name = "testlib_temp_subvolumes",
    srcs = [
        "tests/temp_subvolumes.py",
    ],
    deps = [
        ":find_built_subvol",
        ":fs_utils",
        ":subvol_utils",
    ],
)

python_library(
    name = "unshare",
    srcs = ["unshare.py"],
)

python_unittest(
    name = "test-unshare",
    srcs = ["tests/test_unshare.py"],
    needed_coverage = [(
        100,
        ":unshare",
    )],
)

python_library(
    name = "btrfs_loopback",
    srcs = ["btrfs_loopback.py"],
    deps = [
        ":common",
        ":unshare",
    ],
)

python_library(
    name = "subvol_utils",
    srcs = ["subvol_utils.py"],
    deps = [
        ":btrfs_loopback",
        ":common",
        ":fs_utils",
        ":unshare",
        "//fs_image/compiler:subvolume_on_disk",
    ],
)

python_unittest(
    name = "test-subvol-utils",
    srcs = ["tests/test_subvol_utils.py"],
    needed_coverage = [(
        100,
        ":subvol_utils",
    )],
    resources = {
        TEST_IMAGE_PREFIX + "hello_world_base": "tests/hello-layer",
        TEST_IMAGE_PREFIX + "create_ops-original.sendstream": "tests/create_ops.sendstream",
    },
    deps = [
        ":subvol_utils",
        ":testlib_temp_subvolumes",
        "//fs_image/btrfs_diff:testlib_demo_sendstreams",
        "//fs_image/btrfs_diff:testlib_render_subvols",
    ],
)

python_library(
    name = "volume_for_repo",
    srcs = ["volume_for_repo.py"],
    # `get_volume_for_current_repo()` needs this to be our sibling in the PAR.
    resources = {"set_up_volume.sh"},
    deps = [":fs_utils"],
)

python_unittest(
    name = "test-volume-for-repo",
    srcs = ["tests/test_volume_for_repo.py"],
    needed_coverage = [(
        100,
        ":volume_for_repo",
    )],
    deps = [":volume_for_repo"],
)

python_library(
    name = "artifacts_dir",
    srcs = ["artifacts_dir.py"],
    deps = [":fs_utils"],
)

python_library(
    name = "subvolume_garbage_collector",
    srcs = ["subvolume_garbage_collector.py"],
    deps = [":fs_utils"],
)

python_library(
    name = "find_built_subvol",
    srcs = ["find_built_subvol.py"],
    deps = [
        ":artifacts_dir",
        ":fs_utils",
        ":subvol_utils",
        ":volume_for_repo",
        "//fs_image/compiler:subvolume_on_disk",
    ],
)

python_binary(
    name = "find-built-subvol",
    main_module = "fs_image.find_built_subvol",
    deps = [":find_built_subvol"],
)

python_unittest(
    name = "test-find-built-subvol",
    srcs = ["tests/test_find_built_subvol.py"],
    needed_coverage = [(
        100,
        ":find_built_subvol",
    )],
    # Ensures we can read resources in @mode/opt. "xar" cannot work because
    # `root` cannot access the content of unprivileged XARs.
    par_style = "zip",
    resources = {
        TEST_IMAGE_PREFIX + "hello_world_base": "tests/hello_world_base",
    },
    deps = [":find_built_subvol"],
)

python_binary(
    name = "layer-mount-config",
    srcs = ["layer_mount_config.py"],
    main_module = "fs_image.layer_mount_config",
)

python_unittest(
    name = "test-layer-mount-config",
    srcs = ["tests/test_layer_mount_config.py"],
    needed_coverage = [(100, ":layer-mount-config-library")],
)

export_file(
    name = "fake_sudo.sh",
    src = "tests/fake_sudo.sh",
)

python_library(
    # Separate so we can put `sudo` alone in its own directory
    name = "fake_sudo",
    resources = {":fake_sudo.sh": "fake_sudo/sudo"},
)

python_unittest(
    name = "test-subvolume-garbage-collector",
    srcs = ["tests/test_subvolume_garbage_collector.py"],
    needed_coverage = [(
        100,
        ":subvolume_garbage_collector",
    )],
    deps = [
        ":fake_sudo",
        ":subvolume_garbage_collector",
    ],
)

# No unit-test since this is simple, its output is random, and we are
# unlikely to need to change it.  Be sure to test your changes manually!
python_library(
    name = "subvolume_version",
    srcs = ["subvolume_version.py"],
)

# These binaries are basically a work-around for the fact that `sudo -C`
# is forbidden by default :/

python_binary(
    name = "recv-fds-and-run",
    srcs = ["recv_fds_and_run.py"],
    main_module = "fs_image.recv_fds_and_run",
    par_style = "xar",
    deps = [
        ":common",
        ":fs_utils",
    ],
)

python_library(
    name = "send_fds_and_run",
    srcs = ["send_fds_and_run.py"],
    resources = {":recv-fds-and-run": "recv-fds-and-run"},
    deps = [
        ":common",
        ":fs_utils",
    ],
)

python_unittest(
    name = "test-send-fds-and-run",
    srcs = ["tests/test_send_fds_and_run.py"],
    needed_coverage = [(100, ":send_fds_and_run")],
    # Ensures we can read resources in @mode/opt. "xar" cannot work because
    # `root` cannot access the content of unprivileged XARs.
    par_style = "zip",
    deps = [":send_fds_and_run"],
)

python_binary(
    name = "send-fds-and-run",
    main_module = "fs_image.send_fds_and_run",
    # Ensures we can read resources in @mode/opt. "xar" cannot work because
    # `root` cannot access the content of unprivileged XARs.
    par_style = "zip",
    deps = [":send_fds_and_run"],
)

# These binaries are used by `image_layer.py` as build-time helpers.

python_binary(
    name = "artifacts-dir",
    main_module = "fs_image.artifacts_dir",
    deps = [":artifacts_dir"],
)

python_binary(
    name = "compiler",
    main_module = "fs_image.compiler.compiler",
    # "fastzip" would break :volume_for_repo in @mode/opt.  "xar" fails
    # since `root` cannot access the content of an unprivileged XAR.
    par_style = "zip",
    deps = ["//fs_image/compiler:compiler"],
)

python_binary(
    name = "subvolume-garbage-collector",
    main_module = "fs_image.subvolume_garbage_collector",
    deps = [":subvolume_garbage_collector"],
)

python_binary(
    name = "subvolume-version",
    main_module = "fs_image.subvolume_version",
    deps = [":subvolume_version"],
)

python_binary(
    name = "volume-for-repo",
    main_module = "fs_image.volume_for_repo",
    deps = [":volume_for_repo"],
)

python_library(
    name = "update_package_db",
    srcs = ["update_package_db.py"],
    deps = [
        "//fs_image:common",
        "//fs_image:fs_utils",
    ],
)

python_unittest(
    name = "test-update-package-db",
    srcs = ["tests/test_update_package_db.py"],
    needed_coverage = [(100, ":update_package_db")],
    deps = [":update_package_db"],
)

python_binary(
    name = "package-image",
    srcs = ["package_image.py"],
    main_module = "fs_image.package_image",
    deps = [
        ":find_built_subvol",
        ":subvol_utils",
    ],
)

# Also tests the Buck macro `image_package.bzl`, but we cannot assert coverage.
python_unittest(
    name = "test-package-image",
    srcs = ["tests/test_package_image.py"],
    needed_coverage = [(100, ":package-image-library")],
    # Ensures we can read resources in @mode/opt. "xar" cannot work because
    # `root` cannot access the content of unprivileged XARs.
    par_style = "zip",
    resources = {
        # Same comment re: mutate_ops as in `test_layer_from_demo_sendstreams`.
        TEST_IMAGE_PREFIX + "create_ops-original.sendstream": "tests/create_ops-original.sendstream",
        TEST_IMAGE_PREFIX + "create_ops.sendstream": "tests/create_ops.sendstream",
        TEST_IMAGE_PREFIX + "create_ops": "tests/create_ops.layer",
        TEST_IMAGE_PREFIX + "create_ops-layer-via-tarball-package": "tests/create_ops-layer-via-tarball-package",
    },
    deps = [
        ":find_built_subvol",
        ":package-image-library",
        ":testlib_temp_subvolumes",
        ":unshare",
        "//fs_image/btrfs_diff:testlib_demo_sendstreams",
        "//fs_image/btrfs_diff:testlib_render_subvols",
    ],
)

python_unittest(
    name = "test-execute-installed",
    srcs = ["tests/test_execute_installed.py"],
    # Ensures we can read resources in @mode/opt. "xar" cannot work because
    # `root` cannot access the content of unprivileged XARs.
    par_style = "zip",
    resources = {
        TEST_IMAGE_PREFIX + "installed-executables": "tests/exe-layer",
    },
    deps = ["//fs_image/nspawn_in_subvol:non_booted"],
)

python_library(
    name = "unionfind",
    srcs = ["unionfind.py"],
    deps = [],
)

python_unittest(
    name = "test-unionfind",
    srcs = ["tests/test_unionfind.py"],
    needed_coverage = [
        (100, ":unionfind"),
    ],
    deps = [":unionfind"],
)
