omit_targets = []
extra_srcs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/backtrace-0.3.60/build.rs. Dependencies:
    cc-1.0.68'''

[extra_mapped_srcs]

[platform_fixup]
