load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/testing:image_test.bzl", "image_sh_test")

oncall("antlir")

image.layer(
    name = "parent",
    features = [
        feature.install_text(
            dst = "/foo",
            text = "foo\n",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

package.sendstream_v2(
    name = "parent.sendstream",
    layer = ":parent",
)

image.layer(
    name = "child",
    features = [
        feature.install_text(
            dst = "/bar",
            text = "bar\n",
        ),
    ],
    parent_layer = ":parent",
)

package.sendstream_v2(
    name = "child.sendstream",
    incremental_parent = ":parent.sendstream",
    layer = ":child",
)

image.layer(
    name = "test-layer",
    features = [
        feature.rpms_install(rpms = [
            "bash",
            "btrfs-progs",
            "coreutils",
            "util-linux-core",
        ]),
        feature.install(
            src = ":parent.sendstream",
            dst = "/parent.sendstream",
        ),
        feature.install(
            src = ":child.sendstream",
            dst = "/child.sendstream",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image_sh_test(
    name = "test-incremental",
    allocate_loop_devices = 1,
    # aarch64 user emulation does not support BTRFS_IOC_SET_RECEIVED_SUBVOL
    compatible_with = ["ovr_config//cpu:x86_64"],
    layer = ":test-layer",
    test = "test-incremental.sh",
)
