load("//metalos:defs.bzl", "rust_binary")
load("//metalos/bzl/service:service.bzl", "native_service")

rust_binary(
    name = "demo-service",
    srcs = glob(["src/*.rs"]),
    link_style = "static",
    linker_flags = [
        "-Wl,--strip-all",
    ],
    unittests = False,
    deps = [
        "anyhow",
        "nix",
        "structopt",
    ],
)

native_service(
    name = "layer",
    binary = ":demo-service",
    generator_binary = "//metalos/lib/service/tests/demo_service/generator:generator",
    service_binary_path = "/usr/bin/demo",
    service_name = "metalos.service.demo",
    systemd_service_unit = "metalos.service.demo.service",
    visibility = ["//metalos/lib/service/..."],
)
