load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "buck_label",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "rstest",
        "serde_json",
        "static_assertions",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "once_cell",
        "regex",
        "serde",
        "thiserror",
    ],
)
