[package]
name = "hash_memo"
version = "0.1.0"
authors = ["Facebook <opensource+crates-hash-memo@fb.com>"]
edition = "2018"
description = "memoization/caching of hash values by Hash and Hasher implementations"
readme = "README.md"
repository = "https://github.com/facebookexperimental/rust-shed"
license = "MIT OR Apache-2.0"
keywords = ["cache", "hash", "map", "memo", "memoize", "set"]
categories = ["data-structures"]

[dependencies]
once_cell = "1.4"

[dev-dependencies]
ahash = "0.7.4"
