["dir/symlink-to-file"]
op = 'added'

["dir/symlink-to-file".diff]
mode = 'u+rwx,g+rwx,o+rwx'
user = "root"
group = "root"
file-type = "symlink"
text = '/target'

[symlink-to-dir]
op = 'added'

[symlink-to-dir.diff]
mode = 'u+rwx,g+rwx,o+rwx'
user = "root"
group = "root"
file-type = "symlink"
text = '/dir'
