[package]
name = "fbthrift_framed"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "fbthrift extensions for framed transport"
readme = "../../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
byteorder = "1.3"
bytes = { version = "1.0", features = ["serde"] }
bytes-05 = { package = "bytes", version = "0.5", features = ["serde"] }
tokio-util = { version = "0.3", features = ["codec", "udp"] }

[dev-dependencies]
futures = { version = "0.3.13", features = ["async-await", "compat"] }
tokio = { version = "0.2.25", features = ["full", "test-util"] }
