# @generated
load("@antlir//antlir/antlir2/package_managers/dnf/rules:repo.bzl", "repo_set")

repo_set(name='repos',
         repos=['//snapshot/rpm/centos10-compose/centos-composes/10/CentOS-Stream-10-20250613.0/compose/AppStream/x86_64/os:centos-composes_10_CentOS-Stream-10-20250613.0_compose_AppStream_x86_64_os',
                '//snapshot/rpm/centos10-compose/centos-composes/10/CentOS-Stream-10-20250613.0/compose/BaseOS/x86_64/os:centos-composes_10_CentOS-Stream-10-20250613.0_compose_BaseOS_x86_64_os',
                '//snapshot/rpm/centos10-compose/centos-composes/10/CentOS-Stream-10-20250613.0/compose/CRB/x86_64/os:centos-composes_10_CentOS-Stream-10-20250613.0_compose_CRB_x86_64_os'],
         visibility=['PUBLIC'])
