[package]
name = "failure_ext"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Extensions to failure crate"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
failure = "0.1"
futures = "0.1.31"
slog = { version = "2.5", features = ["max_level_trace"] }

[dev-dependencies]
thiserror = "1.0"
