load("//antlir/antlir2:antlir2_layer.bzl", "antlir2_layer")
load("//antlir/antlir2/feature:defs.bzl", "feature")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

antlir2_layer(
    name = "base",
    features = [
        feature.install(
            src = "//antlir:empty",
            dst = "/a",
            mode = "a+r",
        ),
        feature.ensure_dirs_exist(
            dirs = "/b",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/b/c",
            mode = "a+rx",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

antlir2_layer(
    name = "remove",
    features = [
        feature.remove(path = "/a"),
        feature.remove(path = "/b"),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "remove-test",
    diff = "remove.toml",
    layer = ":remove",
)
