load("//antlir/antlir2:antlir2_layer.bzl", "antlir2_layer")
load("//antlir/antlir2/feature:ensure_dirs_exist.bzl", "ensure_dirs_exist")
load("//antlir/antlir2/feature:install.bzl", "install")
load("//antlir/antlir2/feature:remove.bzl", "remove")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

antlir2_layer(
    name = "base",
    features = [
        install(
            src = "//antlir:empty",
            dst = "/a",
            mode = "a+r",
        ),
        ensure_dirs_exist(
            dirs = "/b",
        ),
        install(
            src = "//antlir:empty",
            dst = "/b/c",
            mode = "a+rx",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

antlir2_layer(
    name = "remove",
    features = [
        remove(path = "/a"),
        remove(path = "/b"),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "remove-test",
    diff = "remove.toml",
    layer = ":remove",
)
