load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

oncall("twimage")

image.layer(
    name = "base",
    features = [
        feature.install(
            src = "//antlir:empty",
            dst = "/a",
        ),
        feature.ensure_dirs_exist(
            dirs = "/b",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/b/c",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "remove",
    features = [
        feature.remove(path = "/a"),
        feature.remove(path = "/b"),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "remove-test",
    diff = "remove.toml",
    diff_type = "file",
    layer = ":remove",
)

image.layer(
    name = "remove-and-reinstall",
    features = [
        feature.remove(path = "/a"),
        feature.install(
            src = "//antlir:empty",
            dst = "/a",
        ),
        feature.remove(path = "/b"),
        feature.ensure_dirs_exist(dirs = "/b"),
        feature.install(
            src = "//antlir:empty",
            dst = "/b/d",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "remove-and-reinstall-test",
    diff = "remove-and-reinstall.toml",
    diff_type = "file",
    layer = ":remove-and-reinstall",
)
