load("//antlir/bzl:build_defs.bzl", "rust_binary")

rust_binary(
    name = "image-test",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "tempfile",
        "tracing",
        "tracing-glog",
        "tracing-subscriber",
        "//antlir:find_root",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/antlir2/features:mount.lib",
        "//antlir/filesystem/absolute_path:absolute_path",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
