load("//antlir/bzl:build_defs.bzl", "buck_command_alias", "export_file", "python_binary", "rust_binary", "rust_library")

oncall("antlir")

rust_library(
    name = "image_test_lib",
    srcs = ["src/lib.rs"],
    visibility = ["PUBLIC"],
    deps = [
        "clap",
        "thiserror",
    ],
)

rust_binary(
    name = "image-test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "serde",
        "tempfile",
        "tracing",
        "tracing-glog",
        "tracing-subscriber",
        ":image_test_lib",
        "//antlir:find_root",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/antlir2/antlir2_rootless:antlir2_rootless",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)

export_file(
    name = "antlir2_image_test.service",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "static-list",
    srcs = ["static_list.py"],
    main_function = "antlir.antlir2.testing.image_test.static_list.main",
)

buck_command_alias(
    name = "static-list-cpp",
    args = ["cpp"],
    exe = ":static-list",
    visibility = ["PUBLIC"],
)

buck_command_alias(
    name = "static-list-py",
    args = ["py"],
    exe = ":static-list",
    visibility = ["PUBLIC"],
)
