load("//antlir/bzl:build_defs.bzl", "export_file", "rust_binary", "rust_library")

oncall("antlir")

rust_library(
    name = "image_test_lib",
    srcs = ["src/lib.rs"],
    visibility = ["PUBLIC"],
    deps = [
        "clap",
        "thiserror",
    ],
)

rust_binary(
    name = "image-test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "loopdev",
        "tempfile",
        "tracing",
        "tracing-glog",
        "tracing-subscriber",
        ":image_test_lib",
        "//antlir:find_root",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/antlir2/features:mount.lib",
        "//antlir/filesystem/absolute_path:absolute_path",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)

export_file(
    name = "antlir2_image_test.service",
    visibility = ["PUBLIC"],
)
