load("//antlir/antlir2/bzl:configured_alias.bzl", "antlir2_configured_alias")
load("//antlir/bzl:build_defs.bzl", "export_file", "python_unittest")

oncall("antlir")

export_file(
    name = "f",
    src = select({
        "//antlir/antlir2/os:centos10": "c10",
        "//antlir/antlir2/os:centos9": "c9",
        "DEFAULT": "default",
    }),
)

antlir2_configured_alias(
    name = "f.c9",
    actual = ":f",
    default_os = "centos9",
)

antlir2_configured_alias(
    name = "f.c10",
    actual = ":f",
    default_os = "centos10",
)

python_unittest(
    name = "test",
    srcs = ["test.py"],
    resources = {
        ":f": "f.default",
        ":f.c10": "f.centos10",
        ":f.c9": "f.centos9",
    },
)
