load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("twimage")

rust_library(
    name = "isolate_cfg",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["//antlir/antlir2/antlir2_isolate/..."],
    deps = [
        "serde",
    ],
)
