load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "lifecycle",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "slog",
        "//metalos/host_configs/rust:metalos_host_configs",
        "//metalos/lib/package_download:package_download",
        "//metalos/lib/state:state",
    ],
)
