load("//antlir/bzl:oss_shim.bzl", "python_binary", "third_party")

python_binary(
    name = "extract",
    srcs = ["extract.py"],
    main_module = "antlir.bzl.genrule.extractor.extract",
    deps = [
        "//antlir:common",
        "//antlir:fs_utils",
        third_party.library(
            "pyelftools",
            platform = "python",
        ),
    ],
)
