load("//antlir/bzl:build_defs.bzl", "export_file")
load("//antlir/bzl:shape.bzl", "shape")

oncall("antlir")

export_file(name = "shape.bzl")

export_file(name = "stat.bzl")

export_file(name = "sha256.bzl")

export_file(
    name = "99-skip-unit.conf",
    src = "files/99-skip-unit.conf",
    visibility = ["PUBLIC"],
)

shape.impl(
    name = "target.shape",
)
