load("//antlir/bzl:rpm_repo_snapshot.bzl", "rpm_repo_snapshot")
load("//platforms:defs.bzl", "fedora_storage_config")

rpm_repo_snapshot(
    name = "fedora33",
    src = "fedora33",
    rpm_installers = ("dnf",),
    storage = fedora_storage_config(33),
)
