# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//antlir/bzl:oss_shim.bzl", "export_file")
load(":defs.bzl", "snapshot", "storage_config")

export_file(
    name = "fedora33/dnf.conf",
)

export_file(
    name = "centos8-stream/dnf.conf",
)

snapshot(
    name = "fedora33",
    src = "fedora33",
    gpg_key_allowlist_dir = "snapshot/fedora33/repos/everything-os/gpg_keys",
    rpm_installers = ("dnf",),
    storage = storage_config("fedora", "33"),
)

snapshot(
    name = "centos8-stream",
    src = "centos8-stream",
    gpg_key_allowlist_dir = "centos8-stream/repos/base-os/gpg_keys",
    rpm_installers = ("dnf",),
    storage = storage_config("centos", "8-stream"),
)
