load("//antlir/bzl:image.bzl", "image")

image.layer(
    name = "fedora",
    features = [
        image.rpms_install([
            "basesystem",
            "coreutils",
        ]),
    ],
    build_opts = image.opts(
        # This is the default, but I am making it explicit since the target is
        # named fedora
        rpm_repo_snapshot = "//snapshot:fedora33",
    ),
)

image.package(
    name = "fedora.btrfs",
    layer = ":fedora",
    seed_device = True,
    writable_subvolume = True,
)
