# @oss-disable[end= ]: load("@fbsource//tools/target_determinator/macros:ci.bzl", "ci")
load("//antlir/antlir2/bzl:configured_alias.bzl", "antlir2_configured_alias")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/bzl:build_defs.bzl", "rust_unittest")

oncall("antlir")

image.layer(
    name = "base",
    features = [
        feature.rpms_install(rpms = [
            "systemd",
        ]),
    ],
)

antlir2_configured_alias(
    name = "rooted",
    actual = ":base",
    rootless = False,
)

antlir2_configured_alias(
    name = "rootless",
    actual = ":base",
    rootless = True,
)

rust_unittest(
    name = "test",
    srcs = ["test.rs"],
    # @oss-disable[end= ]: labels = ci.labels(ci.remove(ci.aarch64())),
    run_env = {
        "ROOTED": "$(exe :rooted[container])",
        "ROOTLESS": "$(exe :rootless[container])",
    },
    deps = [
        "rexpect",
    ],
)
