load("//antlir/bzl:build_defs.bzl", "alias", "rust_binary")
load("//antlir/bzl:internal_external.bzl", "internal_external")

oncall("antlir")

rust_binary(
    name = "makerepo.rc",
    srcs = glob(["src/**/*.rs"]),
    crate = "makerepo",
    visibility = [],
    deps = [
        "anyhow",
        "clap",
        "flate2",
        "hex",
        "quick-xml",
        "serde",
        "serde_json",
        "sha2-010",
    ],
)

alias(
    name = "makerepo",
    actual = internal_external(
        fb = "fbcode//antlir/antlir2/package_managers/dnf/rules/makerepo/facebook/msdk:msdk[makerepo/makerepo]",
        oss = ":makerepo.rc",
    ),
)
