#!/bin/bash -ue
# This is not a real systemd generator, it just sets the NIS domainname
# to mark this VM as "not a build step", as used by `wrap_runtime_deps.bzl`.
#
# It is better for this to be a generator than a unit because:
#
#   - A unit cannot easily prevent other units from racing to start
#     simultaneously.  If a unit with `install_buck_runnable` were to run
#     before the NIS domainname got set, it could fail. On the other hand,
#     generators block all units from starting, which is what we need.
#
#   - As explained in `BuckRunnableVMTest`, under vmtest generators cannot
#     use `install_buck_runnable`, so setting this during the "generator"
#     phase of the `systemd` boot process is early enough for ALL possible
#     uses of `install_buck_runnable`.

# Send any error messages to the kernel console, see `systemd` issue #15638.
: 2>/dev/kmsg && exec 2> /dev/kmsg
: 1>/dev/kmsg && exec 1> /dev/kmsg

# Only set the special NIS domainname if `vmtest.py` added a corresponding
# sigil on the kernel command-line.  This prevents future versions of Antlir
# that have VM-based build steps from accidentally marking those steps as
# "not a build step" -- such a failure could cause incorrect builds due to
# insufficient build target invalidation.
if grep -q ANTLIR_CONTAINER_IS_NOT_PART_OF_A_BUILD_STEP=1 /proc/cmdline ; then
    /usr/libexec/antlir-vmtest/nis_domainname set
fi
