load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_debs_test.bzl", "image_test_deb_names")

oncall("antlir")

image.layer(
    name = "bash-installed",
    default_os = "debian-trixie",
    features = [
        feature.apt_install(
            packages = [
                "bash",
                "dash",
                "dpkg",
            ]
        ),
    ],
)

image_test_deb_names(
    name = "test-bash-installed",
    layer = ":bash-installed",
    names = [
        "bash",
        "dash",
        "dpkg",
    ],
)

image.layer(
    name = "bash-removed",
    default_os = "debian-trixie",
    features = [
        feature.apt_remove(
            packages = [
                "bash",
            ]
        ),
    ],
    parent_layer = ":bash-installed",
)

image_test_deb_names(
    name = "test-bash-removed",
    layer = ":bash-removed",
    names = [
        "bash",
    ],
    not_installed = True,
)
