load("//antlir/bzl:build_defs.bzl", "python_library")
load(":defs.bzl", "buck_isolation_py")

oncall("twimage")

buck_isolation_py(name = "buck_isolation.py")

python_library(
    name = "buck_isolation",
    srcs = {":buck_isolation.py": "buck_isolation.py"},
)
