# This should always exist to define the default and host platform
platform(
    name = "linux-x86_64",
    constraint_values = [
        "//cpu/constraints:x86_64",
        "//os/constraints:linux",
    ],
    visibility = ["PUBLIC"],
)
