load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "state",
    srcs = glob(["src/*.rs"]),
    unittests = [
        "plain",
        "container",
    ],
    deps = [
        "anyhow",
        "serde",
        "serde_json",
        "uuid",
    ],
)
