load("//antlir/antlir2/bzl/flavor:defs.bzl", "flavor")
load("//antlir/antlir2/package_managers/dnf/rules:repo.bzl", "repo_set")

oncall("antlir")

repo_set(
    name = "empty-repo-set",
    repo_sets = [],
    repos = [],
    visibility = [
        "PUBLIC",
    ],
)

flavor(
    name = "none",
    default_dnf_repo_set = ":empty-repo-set",
    rpm_reflink_flavor = None,
    visibility = ["PUBLIC"],
)
