load("@prelude//:rules.bzl", "constraint")
load("//antlir/bzl:build_defs.bzl", "rust_binary", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir2_rootless",
    srcs = glob(["src/**/*.rs"]),
    visibility = [
        "//antlir/...",
        "//externals_builder/bzl/tools/...",
        "//registry/builder/...",
        "//tupperware/cm/antlir2/bzl:",
    ],
    deps = [
        "nix",
        "once_cell",
        "thiserror",
        "tracing",
        "//antlir/antlir2/antlir2_rootless/unshare_userns:unshare_userns",
        "//antlir/antlir2/antlir2_rootless/unshare_userns:unshare_userns_c",
        "//antlir/antlir2/antlir2_userns:antlir2_userns",
    ],
)

rust_binary(
    name = "unshare-userns",
    srcs = ["bin/unshare_userns.rs"],
    deps = [
        "anyhow",
        ":antlir2_rootless",
    ],
)

constraint(
    name = "config",
    default = "rootless",
    values = [
        "rootless",
        "rooted",
    ],
    visibility = ["PUBLIC"],
)
