load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("twimage")

rust_library(
    name = "antlir2_rootless",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "nix",
        "once_cell",
        "thiserror",
        "tracing",
    ],
)
