load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "snapshot",
    srcs = glob(["src/**/*.rs"]),
    test_srcs = glob(["testdata/**"]),
    deps = [
        "anyhow",
        "bon",
        "clap",
        "flate2",
        "hex",
        "liblzma",
        "sequoia-openpgp",
        "serde",
        "serde_json",
        "sha1",
        "sha2",
        "tracing",
        "tracing-subscriber",
        "//antlir/filesystem/stdio_path:stdio_path",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
