load("//antlir/bzl:build_defs.bzl", "rust_binary", "rust_library")

oncall("antlir")

rust_library(
    name = "snapshot_common",
    srcs = glob(["common/src/**/*.rs"]),
    crate_root = "common/src/lib.rs",
    test_deps = [
        "hex-literal",
        "serde_json",
        "serde_starlark",
    ],
    deps = [
        "anyhow",
        "bon",
        "hex",
        "serde",
        "serde_with",
        "sha1-010",
        "sha2",
        "thiserror",
        "tokio",
    ],
)

rust_binary(
    name = "metadata",
    srcs = glob(["metadata/src/**/*.rs"]),
    crate_root = "metadata/src/main.rs",
    link_style = "shared",
    test_deps = [
        "hex-literal",
    ],
    test_srcs = glob(["testdata/**"]),
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "flate2",
        "hex",
        "liblzma",
        "quick-xml",
        "sequoia-openpgp",
        "serde",
        "serde_json",
        "serde_with",
        "tracing",
        "tracing-subscriber",
        ":snapshot_common",
        "//antlir/filesystem/stdio_path:stdio_path",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)

rust_binary(
    name = "snapshot",
    srcs = glob(["snapshot/src/**/*.rs"]),
    crate_root = "snapshot/src/main.rs",
    fb_deps = [
        "//manifold/clients/rust:manifold_client",
    ],
    link_style = "shared",
    test_deps = [
        "hex-literal",
    ],
    deps = [
        "anyhow",
        "async-trait",
        "backoff",
        "cap-std",
        "chrono",
        "clap",
        "fbinit",
        "fbinit-tokio",
        "futures",
        "hex",
        "indicatif",
        "parking_lot",
        "reqwest",
        "serde",
        "serde_json",
        "tempfile",
        "tokio",
        "tracing",
        "tracing-subscriber",
        "typetag",
        "url",
        ":snapshot_common",
        "//antlir:find_root",
        "//antlir/buck2/buck_label:buck_label",
        "//antlir/buck2/buck_targets:buck_targets",
        "//antlir/filesystem/stdio_path:stdio_path",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
