load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "snapshot",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    fb_deps = [
        "//manifold/clients/rust:manifold_client",
    ],
    link_style = "shared",
    test_srcs = glob(["testdata/**"]),
    deps = [
        "anyhow",
        "async-trait",
        "bon",
        "clap",
        "fbinit",
        "fbinit-tokio",
        "flate2",
        "futures",
        "hex",
        "liblzma",
        "reqwest-0-13",
        "sequoia-openpgp",
        "serde",
        "serde_json",
        "sha1",
        "sha2",
        "tempfile",
        "tokio",
        "tracing",
        "tracing-subscriber",
        "url",
        "walkdir",
        "//antlir/filesystem/stdio_path:stdio_path",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
