load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "working_format",
    default = "btrfs",
    values = [
        "btrfs",
        "cad-stack",
    ],
    visibility = ["PUBLIC"],
)

constraint(
    name = "exec_mode",
    default = "prefer-local",
    values = [
        "force-local",
        "force-remote",
        "prefer-local",
    ],
    visibility = ["PUBLIC"],
)
