load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "working_format",
    default = "btrfs",
    values = [
        "btrfs",
        "cad-stack",
    ],
    visibility = ["PUBLIC"],
)
