# @noautodeps

load("//antlir/bzl:oss_shim.bzl", "buck_genrule")
load("//metalos:defs.bzl", "rust_binary", "rust_library")

rust_binary(
    name = "serialize-host-struct",
    srcs = ["serialize_host_struct.rs"],
    unittests = False,
    deps = [
        "anyhow",
        "bytes",
        "clap",
        "fbthrift",
        ":example_host_for_tests",
        "//metalos/host_configs/rust:metalos_host_configs",
    ],
)

rust_library(
    name = "example_host_for_tests",
    srcs = ["example_host_for_tests.rs"],
    deps = [
        "//metalos/host_configs:api-rust",
        "//metalos/host_configs/rust:metalos_host_configs",
    ],
)

buck_genrule(
    name = "example-host-for-tests.json",
    cmd = "$(exe :serialize-host-struct) --example > $OUT",
    visibility = ["PUBLIC"],
)
