# @noautodeps

load("//metalos:defs.bzl", "rust_binary")

rust_binary(
    name = "serialize-host-struct",
    srcs = ["serialize_host_struct.rs"],
    deps = [
        "anyhow",
        "bytes",
        "fbthrift",
        "//metalos/host_configs:api-rust",
    ],
)
