[package]
name = "slog_glog_fmt"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "slog Drain for glog-formatted logs"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[[bin]]
name = "slog_glog_fmt_example"
path = "example/main.rs"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["clock", "serde", "std"], default-features = false }
failure_ext = { version = "0.1.0", path = "../failure_ext" }
hostname = "0.3"
itertools = "0.10.1"
nix = "0.20"
slog = { version = "2.5", features = ["max_level_trace", "nested-values"] }
slog-term = "2.4.2"

[dev-dependencies]
lazy_static = "1.0"
rand = { version = "0.7", features = ["small_rng"] }
regex = "1.4.2"
thiserror = "1.0"
