load("//antlir/antlir2:antlir2_layer.bzl", "antlir2_layer")
load("//antlir/antlir2/feature:clone.bzl", "clone")
load("//antlir/antlir2/feature:ensure_dirs_exist.bzl", "ensure_dirs_exist", "ensure_subdirs_exist")
load("//antlir/antlir2/feature:install.bzl", "install")
load("//antlir/antlir2/feature:symlink.bzl", "ensure_file_symlink")
load("//antlir/antlir2/feature:usergroup.bzl", "group_add", "user_add")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

antlir2_layer(
    name = "base",
    features = [
        ensure_dirs_exist(
            dirs = "/etc",
        ),
        install(
            src = "//antlir/antlir2/test_images:passwd",
            dst = "/etc/passwd",
            mode = "a+r,u+w",
        ),
        install(
            src = "//antlir/antlir2/test_images:group",
            dst = "/etc/group",
            mode = "a+r,u+w",
        ),
        install(
            src = "//antlir:empty",
            dst = "/fakeshell",
            mode = "a+rx",
        ),
        user_add(
            home_dir = "/",
            primary_group = "antlir",
            shell = "/fakeshell",
            username = "antlir",
        ),
        group_add(
            groupname = "antlir",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

antlir2_layer(
    name = "clone-src",
    features = [
        install(
            src = "file-to-clone",
            dst = "/f",
            group = "antlir",
            mode = "a+r",
            user = "antlir",
        ),
        ensure_dirs_exist(
            dirs = "/path/to/clone/dir",
        ),
        ensure_subdirs_exist(
            group = "antlir",
            into_dir = "/path/to/clone/dir",
            subdirs_to_create = "deeper/nesting",
            user = "antlir",
        ),
        install(
            src = "file-to-clone",
            dst = "/path/to/clone/dir/deeper/nesting/foo",
            mode = "a+r",
        ),
        ensure_file_symlink(
            link = "/path/to/clone/dir/cloned-symlink",
            target = "/f",
        ),
    ],
    parent_layer = ":base",
)

antlir2_layer(
    name = "clone-file",
    features = [
        clone(
            dst_path = "/cloned-file",
            src_layer = ":clone-src",
            src_path = "/f",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "clone-file-test",
    diff = "clone-file.toml",
    layer = ":clone-file",
)

antlir2_layer(
    name = "clone-dir",
    features = [
        clone(
            dst_path = "/cloned",
            src_layer = ":clone-src",
            src_path = "/path/to/clone/dir",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "clone-dir-test",
    diff = "clone-dir.toml",
    layer = ":clone-dir",
)

antlir2_layer(
    name = "clone-dir-omit-outer",
    features = [
        ensure_dirs_exist(dirs = "/cloned"),
        clone(
            dst_path = "/cloned/",
            src_layer = ":clone-src",
            src_path = "/path/to/clone/dir/",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "clone-dir-omit-outer-test",
    # This is intentionally the same as ':clone-dir', see the comment in the
    # toml file for details
    diff = "clone-dir.toml",
    layer = ":clone-dir-omit-outer",
)

antlir2_layer(
    name = "clone-dir-pre-existing",
    features = [
        ensure_dirs_exist(dirs = "/clone/into/existing"),
        clone(
            dst_path = "/clone/into/existing/",
            src_layer = ":clone-src",
            src_path = "/path/to/clone/dir",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "clone-dir-pre-existing-test",
    diff = "clone-dir-pre-existing.toml",
    layer = ":clone-dir-pre-existing",
)

antlir2_layer(
    name = "base-ids-remap",
    features = [
        ensure_dirs_exist(
            dirs = "/etc",
        ),
        install(
            src = "//antlir/antlir2/test_images:passwd",
            dst = "/etc/passwd",
            mode = "a+r,u+w",
        ),
        install(
            src = "//antlir/antlir2/test_images:group",
            dst = "/etc/group",
            mode = "a+r,u+w",
        ),
        install(
            src = "//antlir:empty",
            dst = "/fakeshell",
            mode = "a+rx",
        ),
        user_add(
            home_dir = "/",
            primary_group = "antlir",
            shell = "/fakeshell",
            uid = 10,
            username = "antlir",
        ),
        group_add(
            gid = 10,
            groupname = "antlir",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

antlir2_layer(
    name = "clone-file-remap-ids",
    features = [
        clone(
            dst_path = "/cloned-file",
            src_layer = ":clone-src",
            src_path = "/f",
        ),
    ],
    parent_layer = ":base-ids-remap",
)

image_diff_test(
    name = "clone-file-remap-ids-test",
    # same user and group names but different ids
    diff = "clone-file.toml",
    layer = ":clone-file-remap-ids",
)
