# This reproduces the cloned directory into a new location
# It produces the same result for both of the layers that use this as the
# expected diff assertion:
# 1) simply cloning the '/path/to/clone/dir' directory to '/cloned'
# 2) pre-creating '/cloned' and cloning '/path/to/clone/dir/' into '/cloned/'

[file.cloned]
op = 'added'

[file.cloned.diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "root"
group = "root"
content_hash = "0"

[file."cloned/cloned-symlink"]
op = 'added'

[file."cloned/cloned-symlink".diff]
mode = 'u+rwx,g+rwx,o+rwx'
file-type = 'symlink'
user = "root"
group = "root"
text = '/f'

[file."cloned/deeper"]
op = 'added'

[file."cloned/deeper".diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "antlir"
group = "antlir"
content_hash = "0"

[file."cloned/deeper/nesting"]
op = 'added'

[file."cloned/deeper/nesting".diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = "antlir"
group = "antlir"
content_hash = "0"

[file."cloned/deeper/nesting/foo"]
op = 'added'

[file."cloned/deeper/nesting/foo".diff]
mode = 'u+r,g+r,o+r'
file-type = 'regular-file'
user = "root"
group = "root"
text = '''
This file will be cloned!
'''
