load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "test-depgraph",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "clap",
        "regex",
        "tempfile",
        "//antlir/antlir2/antlir2_depgraph:antlir2_depgraph",
        "//antlir/antlir2/antlir2_depgraph_if:antlir2_depgraph_if",
        "//antlir/antlir2/antlir2_facts:antlir2_facts",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
