load("//antlir/bzl:build_defs.bzl", "rust_binary")

rust_binary(
    name = "test-depgraph",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "clap",
        "regex",
        "//antlir/antlir2/antlir2_depgraph:antlir2_depgraph",
        "//antlir/antlir2/antlir2_features:antlir2_features",
        "//antlir/buck/buck_label:buck_label",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
