load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")
load("//antlir/bzl:build_defs.bzl", "python_unittest")
load(":defs.bzl", "outer")

oncall("antlir")

outer(
    name = "defaults",
)

outer(
    name = "override",
    cpu = "foo",
)

python_unittest(
    name = "tests",
    srcs = ["tests.py"],
    network_access = network_access_utils.all(),
    resources = {
        ":defaults": "defaults",
        ":override": "override",
    },
)
