load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")

oncall("antlir")

image.layer(
    name = "busybox-src",
    features = [
        feature.rpms_install(rpms = ["busybox"]),
    ],
    visibility = ["PUBLIC"],
)
