load("//antlir/bzl:build_defs.bzl", "rust_library")

rust_library(
    name = "features",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "serde",
        "//antlir/buck/buck_label:buck_label",
    ],
)
