#!/bin/sh

# Why this script?
#
# TL;DR this is how we trick the rootfs systemd that, it is not "switched-root" from an initrd systemd.
#
# Without this shim script, the initrd's systemd will `exec` rootfs systemd
# binary with arguments:
# /usr/lib/systemd/systemd --switched-root --deserialize <a file descriptor>
# which is how the initrd systemd passes state information to the rootfs
# systemd.
#
# However we don't want that, because the "state passing" ties the two systemd together, which
# results in:
# 1. We need to always make sure the two systemd versions are compatible. This can be hard because we
#    build and ship our initrd and rootfs separately;
# 2. Changing one might result in weird behaviors in the other. I've seen a couple of times already,
#    that changes in the initrd systemd made a complete mess in the rootfs systemd dependency ordering.
#    You probably don't want to debug issues like that, ever.
#
# With this shim script however, the rootfs systemd is started fresh and completed disconnected from
# the initrd systemd. This enables us to dev, build and ship the initrd and the rootfs separately without
# any concerns.
#
# The drawbacks (as seen so far):
# 1. Something might get re-run in rootfs systemd thus slow down boot time. However in my experiments
#    the time increase is neglectable.
# 2. After switch-root, `systemd-analyze` won't have pre-switch-root data. However, `journalctl` still
#    can print logs of pre-switch-root units.
#
# References:
# 1. https://man7.org/linux/man-pages/man1/systemctl.1.html (grep for switch-root ROOT [INIT])
# 2. https://unix.stackexchange.com/a/197485

exec /usr/lib/systemd/systemd
