load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/features/mknod:mknod.bzl", "device_type")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

oncall("antlir")

image.layer(
    name = "base",
    features = [
        feature.ensure_dirs_exist(
            dirs = "/etc",
        ),
        feature.install_text(
            dst = "/etc/passwd",
            mode = "a+r,u+w",
            text = "root:x:0:0:root:/root:/bin/bash\nantlir:x:1000:1000::/:/fakeshell\n",
        ),
        feature.install_text(
            dst = "/etc/group",
            mode = "a+r,u+w",
            text = "root:x:0:\nantlir_group:x:1000:\n",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "mknod",
    features = [
        feature.mknod(
            dst = "/console",
            group = "antlir_group",
            major = 5,
            minor = 1,
            mode = 0o000,
            type = device_type("char"),
            user = "antlir",
        ),
        feature.mknod(
            dst = "/random",
            group = "antlir_group",
            major = 1,
            minor = 8,
            mode = 0o654,
            type = device_type("char"),
            user = "antlir",
        ),
        feature.mknod(
            dst = "/urandom",
            group = "antlir_group",
            major = 1,
            minor = 9,
            mode = 0o000,
            type = device_type("char"),
            user = "antlir",
        ),
        # not all device types are allowed by sandcastle, lets limit the test to allowed ones
        # feature.mknod(
        #     dst = "/tty",
        #     group = "antlir_group",
        #     major = 5,
        #     minor = 0,
        #     mode = 0o000,
        #     type = device_type("char"),
        #     user = "antlir",
        # ),
        # feature.mknod(
        #     dst = "/ttyS0",
        #     group = "antlir_group",
        #     major = 4,
        #     minor = 64,
        #     mode = 0o000,
        #     type = device_type("char"),
        #     user = "antlir",
        # ),
        # feature.mknod(
        #     dst = "/ttyS1",
        #     group = "antlir_group",
        #     major = 4,
        #     minor = 65,
        #     mode = 0o000,
        #     type = device_type("char"),
        #     user = "antlir",
        # ),
        # feature.mknod(
        #     dst = "/tpm0",
        #     group = "antlir_group",
        #     major = 10,
        #     minor = 224,
        #     mode = 0o000,
        #     type = device_type("char"),
        #     user = "antlir",
        # ),
        feature.mknod(
            dst = "/test2",
            major = 42,
            minor = 49,
            mode = "u+r",
            type = device_type("block"),
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "mknod-test",
    diff = "mknod.toml",
    diff_type = "file",
    layer = ":mknod",
)
