load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "package_manager",
    default = "none",
    values = [
        "none",
        "dnf",
        "dnf5",
        "apt",
    ],
    visibility = ["PUBLIC"],
)
