load("//antlir/buck2/bzl:toolchain.bzl?v2_only", "antlir_toolchain")
load("//antlir/bzl:build_defs.bzl", "is_buck2")

antlir_toolchain(
    name = "toolchain",
    artifacts_dir = "//antlir:artifacts-dir",
    visibility = ["PUBLIC"],
    volume_for_repo = "//antlir:volume-for-repo",
) if is_buck2() else None
