load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:xar.bzl", "xar")
load("//antlir/bzl:build_defs.bzl", "python_unittest")

oncall("antlir")

image.layer(
    name = "layer",
    features = [
        feature.install_text(
            dst = "/foo",
            text = "foo\n",
        ),
        feature.install(
            src = "entrypoint.sh",
            dst = "/entrypoint",
            mode = "a+rx",
        ),
    ],
)

xar(
    name = "test.xar",
    executable = "/entrypoint",
    layer = ":layer",
)

python_unittest(
    name = "test-xar",
    srcs = ["test.py"],
    resources = {":test.xar": "test.xar"},
)
