[package]
name = "sql"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Crate for accessing sql databases"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
cloned = { version = "0.1.0", path = "../cloned" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
futures-util = "0.3.7"
futures_ext = { version = "0.1.0", path = "../futures_ext" }
mysql_async = "0.23"
rusqlite = { version = "0.23", features = ["blob"] }
sql_common = { version = "0.1.0", path = "common" }

[dev-dependencies]
fbinit-tokio-02 = { version = "0.1.0", path = "../fbinit/fbinit-tokio-02" }
sql_tests_lib = { version = "0.1.0", path = "tests_lib" }
tokio = { version = "0.2.25", features = ["full", "test-util"] }
