load("@fbcode_macros//build_defs:export_files.bzl", "export_file")
load(":suite.bzl", "suite")

oncall("antlir")

export_file(
    name = "dummy_signing_key",
    src = "keys/dummy.secret.pgp",
)

suite(
    name = "trixie",
    architectures = [
        "amd64",
        "arm64",
    ],
    archive_url = "https://mirror.facebook.net/debian",
    components = [
        "main",
        "contrib",
    ],
    # TODO: these are temporarily hardcoded to get moving faster with CI builds
    # (download_file works where curl does not). The minimum "snapshot" process
    # would just be updating these hashes, but a proper deterministic/persistent
    # snapshot is a P0 for this effort so we can deal with a few diffs in this
    # stack that keep it hardcoded
    inrelease_checksums = {
        "sha1": "ca4c891ee6114d2a800cc3b2675a36847ecc1da8",
        "sha256": "7592e4ccb4658a58bfe485d3356b3c983bf8ccff7fca1f6091e4d4296284ed18",
    },
    visibility = ["PUBLIC"],
)
