load("@fbcode_macros//build_defs:export_files.bzl", "export_file")
load(":suite.bzl", "suite")

oncall("antlir")

export_file(
    name = "dummy_signing_key",
    src = "keys/dummy.secret.pgp",
)

suite(
    name = "trixie",
    architectures = [
        "amd64",
        "arm64",
    ],
    archive_url = "https://mirror.facebook.net/debian",
    components = [
        "main",
        "contrib",
    ],
    snapshot_storage = {
        "api_key": "antlir_snapshots-key",
        "bucket": "antlir_snapshots",
        "type": "manifold",
    },
    visibility = ["PUBLIC"],
)
