load("//antlir/bzl:build_defs.bzl", "alias")

oncall("antlir")

alias(
    name = "test-image-flavor",
    actual = "//antlir/antlir2/facebook/flavor:centos-latest",
    visibility = ["//antlir/..."],
)
