load("//antlir/bzl:build_defs.bzl", "alias", "export_file")

oncall("antlir")

alias(
    name = "test-image-flavor",
    actual = "//antlir/antlir2/facebook/flavor:centos-latest",
    visibility = ["//antlir/..."],
)

export_file(
    name = "passwd",
)

export_file(
    name = "group",
)
