# @noautodeps

load("//antlir/bzl:kernel_shim.bzl", "kernels")
load("//antlir/bzl:oss_shim.bzl", "export_file")
load("//antlir/vm/bzl:initrd.bzl", "initrd")

oncall("twimage")

export_file(
    name = "modules.conf",
)

# build a vmtest initrd for every kernel
[initrd(kernel = kernels.get(uname)) for uname in kernels.versions.keys()]
