load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl/image/feature:defs.bzl", "feature")

image.layer(
    name = "example",
    parent_layer = "//images/base:fedora",
    features = [
        # this is provided in the base image, so must be removed first
        feature.remove("/etc/motd"),
        image.install("motd", "/etc/motd"),
    ],
)
