load("//antlir/bzl:image.bzl", "image")

image.layer(
    name = "example",
    parent_layer = "//images/base:fedora",
    features = [
        # this is provided in the base image, so must be removed first
        image.remove("/etc/motd"),
        image.install("motd", "/etc/motd"),
    ],
)
