load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")

oncall("antlir")

image.layer(
    name = "layer",
    features = [
        feature.ensure_dirs_exist(
            dirs = "/etc",
        ),
        feature.install_text(
            dst = "/etc/passwd",
            text = "root:x:0:0:root:/root:/bin/bash\n",
        ),
        feature.install_text(
            dst = "/etc/group",
            mode = "a+r,u+w",
            text = "root:x:0:\n",
        ),
        feature.user_add(
            home_dir = "/",
            primary_group = "antlir",
            shell = "/fakeshell",
            uid = 42,
            username = "antlir",
        ),
        feature.group_add(
            gid = 43,
            groupname = "antlir",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/fakeshell",
            mode = "a+rx",
        ),
        feature.install_text(
            dst = "/foo/bar/hello",
            group = "antlir",
            text = "Hello world\n",
            user = "antlir",
            xattrs = {
                "user.foo": "bar",
            },
        ),
        feature.ensure_dirs_exist(
            dirs = "/foo/bar",
        ),
    ],
)

package.sendstream_v2(
    name = "layer.sendstream.v2",
    layer = ":layer",
)

package.sendstream_v2(
    name = "named.sendstream.v2",
    layer = ":layer",
    volume_name = "named",
)

package.sendstream_v2(
    name = "named.sendstream.v2.rootless",
    layer = ":layer",
    rootless = True,
    volume_name = "named",
)
