load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/bzl:build_defs.bzl", "internal_external", "rust_unittest")

oncall("antlir")

image.layer(
    name = "test-layer",
    dnf_additional_repos = [
        "//antlir/antlir2/features/rpm/tests/repo:test-repo",
    ],
    features = [
        ":user",
        feature.rpms_install(rpms = [
            "foobar",
            "foo-epoch",
            "antlir2-changelog",
            "coreutils",
            "systemd",
        ]),
        feature.install(
            src = "//antlir:empty",
            dst = "/feature/foo",
            group = "antlir",
            user = "antlir",
        ),
        feature.ensure_dirs_exist(
            dirs = "/feature/bar",
            group = "antlir",
            user = "antlir",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/feature/bar/baz",
            group = "antlir",
            user = "antlir",
        ),
        feature.ensure_file_symlink(
            link = "/feature/bar/qux",
            target = "/feature/bar/baz",
        ),
        feature.genrule(
            cmd = [
                "ln",
                "-s",
                "target",
                "/relative-symlink",
            ],
            user = "root",
        ),
        feature.install(
            src = "foo.service",
            dst = "/etc/systemd/system/foo.service",
        ),
    ],
)

# These features aren't that interesting, just some boilerplate to ensure that
# the antlir user exists
feature.new(
    name = "user",
    features = [
        feature.install_text(
            dst = "/etc/passwd",
            mode = "a+r,u+w",
            text = "root:x:0:0:root:/root:/bin/bash\n",
        ),
        feature.install_text(
            dst = "/etc/group",
            mode = "a+r,u+w",
            text = "root:x:0:\n",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/fakeshell",
            mode = "a+rx",
        ),
        feature.user_add(
            home_dir = "/",
            primary_group = "antlir",
            shell = "/fakeshell",
            uid = 42,
            username = "antlir",
        ),
        feature.group_add(
            gid = 43,
            groupname = "antlir",
        ),
    ],
)

image.layer(
    name = "child-layer",
    features = [
        feature.remove(path = "/feature/foo"),
        feature.rpms_remove(rpms = ["foobar"]),
        feature.remove(path = "/etc/systemd/system/foo.service"),
        feature.genrule(
            bash = "userdel antlir",
            user = "root",
        ),
    ],
    parent_layer = ":test-layer",
)

rust_unittest(
    name = "test-db-contents",
    srcs = ["test_db_contents.rs"],
    labels = internal_external(
        fb = [],
        oss = ["disabled"],  # buck_resources does not exist in oss
    ),
    resources = {
        "child_db": ":child-layer[debug][facts]",
        "test_db": ":test-layer[debug][facts]",
    },
    deps = [
        "tracing",
        "tracing-test",
        "//antlir/antlir2/antlir2_facts:antlir2_facts",
        "//antlir/antlir2/antlir2_systemd:antlir2_systemd",
    ] + internal_external(
        fb = ["fbsource//third-party/rust:buck-resources"],
        oss = [],
    ),
)
