/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

use super::path::VerifiedPath;

/// A marker trait indicating that this struct is actually
/// generated by the antlir image library
pub trait AntlirLayer {
    fn new_unchecked(base_path: VerifiedPath) -> Self;
}

#[macro_export]
macro_rules! generate_layer {
    ($name:ident { paths: $paths_type:ty $(,)* }) => {
        pub struct $name {
            pub paths: $paths_type,
        }

        impl $crate::antlir_image::layer::AntlirLayer for $name {
            fn new_unchecked(base_path: VerifiedPath) -> Self {
                Self {
                    paths: <$paths_type>::new_unchecked(base_path),
                }
            }
        }
    };
}
