# @noautodeps

load("//antlir/bzl:flavor_helpers.bzl", "flavor_helpers")
load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl/image/feature:defs.bzl", "feature")
load("//antlir/bzl/image/package:btrfs.bzl", "btrfs")
load("//antlir/bzl/image/package:defs.bzl", "package")
load(":disk.bzl", "disk")

# This layer is mounted at /run/fs/control on MetalOS systems, and is the root
# subvolume hierarchy. It contains the below directories to serve as places to
# store subvolumes for MetalOS images and runtime state
image.layer(
    name = "control",
    flavor = flavor_helpers.get_antlir_linux_flavor(),
    features = [],
    visibility = ["//metalos/..."],
)

btrfs.new(
    name = "control.btrfs",
    opts = btrfs.opts.new(
        subvols = {
            "/volume": btrfs.opts.subvol.new(
                layer = ":control",
                writable = True,
            ),
        },
        default_subvol = "/volume",
        loopback_opts = image.opts(
            label = "/",
        ),
    ),
    visibility = ["//metalos/disk/..."],
)

image.layer(
    name = "empty-efi",
    flavor = flavor_helpers.get_antlir_linux_flavor(),
    features = [
        feature.ensure_dirs_exist("/EFI"),
    ],
)

package.new(
    name = "empty-efi.vfat",
    layer = ":empty-efi",
    format = "vfat",
    loopback_opts = image.opts(
        fat_size = 16,
        size_mb = 256,
    ),
    visibility = ["//metalos/..."],
)

disk(
    name = "metalos-gpt-image",
    efi_vfat = ":empty-efi.vfat",
    root_btrfs = ":control.btrfs",
    visibility = ["//metalos/..."],
)
