load("//antlir/bzl:oss_shim.bzl", "python_unittest")

python_unittest(
    name = "test-fake-pty",
    srcs = ["test_fake_pty.py"],
    needed_coverage = [(
        100,
        "//antlir/rpm/replay:fake_pty",
    )],
    deps = [
        "//antlir:fs_utils",
        "//antlir/rpm/replay:fake_pty",
    ],
)
