load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "metalos_mount",
    srcs = ["src/lib.rs"],
    deps = [
        "mockall",
        "nix",
        "slog",
        "thiserror",
        "//metalos/antlir_image/antlir_image:antlir_image",
    ],
)
