load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

rust_library(
    name = "permission_checker",
    srcs = ["src/lib.rs"],
    deps = [
        "fbsource//third-party/rust:thiserror",
        "//common/rust/identity:identity",
    ],
)
