load("//antlir/bzl:template.bzl", "template")

template(
    name = "resolv",
    srcs = ["resolv.jinja2"],
    visibility = [
        "//antlir/linux/...",
        "//images/...",
        "//tupperware/image/vmtest/impl/...",
    ],
)
