load("//antlir/bzl:shape.bzl", "shape")
load("//antlir/bzl:template.bzl", "template")

oncall("antlir")

template(
    name = "resolv",
    srcs = ["resolv.jinja2"],
    visibility = ["PUBLIC"],
)

shape.impl(
    name = "resolv.shape",
)
