load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")

image.layer(
    name = "vfat-layer",
    features = [
        feature.ensure_dirs_exist(dirs = "/EFI/BOOT"),
        feature.install(
            src = "//antlir:empty",
            dst = "/EFI/BOOT/test",
            mode = "a+rx",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

package.vfat(
    name = "vfat-layer.vfat",
    fat_size = 16,
    label = "NONE",
    layer = ":vfat-layer",
    size_mb = 32,
)

package.cpio_gz(
    name = "vfat-layer.cpio.gz",
    layer = ":vfat-layer",
)

package.cpio_zst(
    name = "vfat-layer.cpio.zst",
    layer = ":vfat-layer",
)
