load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:btrfs.bzl", "BtrfsSubvol")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/bzl/package:gpt.bzl", "Partition", "PartitionType")

image.layer(
    name = "btrfs-test-1",
    features = [
        feature.ensure_dirs_exist(dirs = "/btrfs_test_1"),
        feature.ensure_dirs_exist(dirs = "/btrfs_test_2_mnt"),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "btrfs-test-2",
    features = [
        feature.ensure_dirs_exist(dirs = "/btrfs_test_2"),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "btrfs-test-3",
    features = [
        feature.ensure_dirs_exist(dirs = "/btrfs_test_3"),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "vfat-layer",
    features = [
        feature.ensure_dirs_exist(dirs = "/EFI/BOOT"),
        feature.install(
            src = "//antlir:empty",
            dst = "/EFI/BOOT/test",
            mode = "a+rx",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

package.vfat(
    name = "vfat-layer.vfat",
    fat_size = 16,
    label = "NONE",
    layer = ":vfat-layer",
    size_mb = 32,
)

package.cpio_gz(
    name = "vfat-layer.cpio.gz",
    layer = ":vfat-layer",
)

package.cpio_zst(
    name = "vfat-layer.cpio.zst",
    layer = ":vfat-layer",
)

package.sendstream_v2(
    name = "btrfs-test-3.sendstream.v2",
    layer = ":btrfs-test-3",
)

package.sendstream_zst(
    name = "btrfs-test-3.sendstream.zst",
    layer = ":btrfs-test-3",
)

package.sendstream(
    name = "btrfs-test-3.sendstream",
    layer = ":btrfs-test-3",
)

package.squashfs(
    name = "vfat-layer.squashfs",
    layer = ":vfat-layer",
)

package.btrfs(
    name = "btrfs-layer-test.btrfs",
    compression_level = 2,
    default_subvol = "/",
    free_mb = 10,
    label = "test-btrfs",
    subvols = {
        "/test_1": BtrfsSubvol(
            layer = ":btrfs-test-1",
        ),
        "/test_1/btrfs_test_2_mnt": BtrfsSubvol(
            layer = ":btrfs-test-2",
            writable = True,
        ),
        "/test_3": BtrfsSubvol(
            layer = ":btrfs-test-3",
            writable = False,
        ),
    },
)

package.tar_gz(
    name = "vfat-layer.tar.gz",
    layer = ":vfat-layer",
)

package.gpt(
    name = "test-disk.gpt",
    partitions = [
        Partition(
            src = ":vfat-layer.vfat",
            type = PartitionType("esp"),
        ),
        Partition(
            src = ":btrfs-layer-test.btrfs",
            label = "/",
        ),
    ],
)
