load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

oncall("antlir")

image.layer(
    name = "base",
    features = [
        feature.ensure_dirs_exist(
            dirs = "/dir",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/target",
            mode = "a+rx",
        ),
    ],
)

image.layer(
    name = "symlink",
    features = [
        feature.ensure_dir_symlink(
            link = "/symlink-to-dir",
            target = "/dir",
        ),
        feature.ensure_file_symlink(
            link = "/dir/symlink-to-file",
            target = "/target",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "symlink-test",
    diff = "symlink.toml",
    diff_type = "file",
    layer = ":symlink",
)

image.layer(
    name = "features-under-symlinks-base",
    features = [
        feature.rpms_install(rpms = [
            "bash",
            "coreutils",
        ]),
        feature.genrule(
            cmd = [
                "/bin/bash",
                "-c",
                "mkdir -p /path/to/target && ln -s target /path/to/relative",
            ],
            user = "root",
        ),
        feature.ensure_dirs_exist(dirs = "/other/path"),
        feature.ensure_dir_symlink(
            link = "/other/path/symlink",
            target = "/path/to/target",
        ),
    ],
    parent_layer = ":base",
)

image.layer(
    name = "features-under-symlinks",
    features = [
        feature.install_text(
            dst = "/path/to/relative/installed-under-relative-link",
            text = "installed under relative link",
        ),
        feature.install_text(
            dst = "/other/path/symlink/installed-under-absolute-link",
            text = "installed under absolute link",
        ),
    ],
    parent_layer = ":features-under-symlinks-base",
)

image_diff_test(
    name = "features-under-symlink-test",
    diff = "features-under-symlink.toml",
    diff_type = "file",
    layer = ":features-under-symlinks",
)
