load("//antlir/bzl:oss_shim.bzl", "buck_filegroup")

buck_filegroup(
    name = "all-srcs",
    srcs = glob(
        [
            "**/*",
            "**/.*",
        ],
        exclude = [
            "**/facebook/**",
            "**/fb/**",
            "**/*.facebook",
            "**/fbpkg/**",
        ],
    ),
    visibility = [
        "//antlir/facebook/oss-ci:generated",
        "//antlir/facebook/oss-ci:oss-view",
    ],
)
