load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

rust_binary(
    name = "isolate_unshare_preexec",
    srcs = glob(["src/**/*.rs"]),
    compatible_with = [
        "ovr_config//os:linux",
    ],
    visibility = ["//antlir/antlir2/antlir2_isolate/isolate_unshare:"],
    deps = [
        "anyhow",
        "cap-std",
        "clap",
        "nix",
        "//antlir/antlir2/antlir2_isolate/isolate_cfg:isolate_cfg",
        "//antlir/util/cli/json_arg:json_arg",
    ],
)
