load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")

image.layer(
    name = "build-appliance.rpms",
    features = [
        feature.rpms_install(rpms = [
            "chef",
            "cpio",
            "dnf",
            "dosfstools",
            "mtools",
            "fb-chef-solo-tools",
            "python3-dnf-plugin-cow",
            "socat",
            "strace",
            "systemd-container",
        ]),
    ],
    flavor = "//antlir/antlir2/facebook/flavor:centos9",
    visibility = [":build-appliance"],
)

# This is a separate layer because the depgraph does not yet understand files
# that come from rpms. I will address that shortly and re-combine this into one
# layer target
image.layer(
    name = "build-appliance",
    features = [
        feature.remove(path = "/etc/yum.repos.d"),
        feature.remove(path = "/etc/dnf/dnf.conf"),
        feature.ensure_dirs_exist(dirs = "/antlir"),
    ],
    parent_layer = ":build-appliance.rpms",
)

package.new(
    name = "build-appliance.sendstream.v2",
    format = "sendstream.v2",
    layer = ":build-appliance",
)
