load("//antlir/antlir2/features:defs.bzl", "feature_impl")

oncall("antlir")

feature_impl(
    name = "extend_facts",
    visibility = ["//antlir/antlir2/features/test_only_features/extend_facts/tests/..."],
)
