load("//metalos:defs.bzl", "rust_binary")

rust_binary(
    name = "generator",
    srcs = ["src/generator.rs"],
    autocargo = {"ignore_rule": True},
    link_style = "static",
    linker_flags = [
        "-Wl,--strip-all",
    ],
    deps = [
        "anyhow",
        "fbthrift",
        "maplit",
        "//metalos/lib/service:service_config_generator_if-rust",
    ],
)
