load("//antlir/bzl:build_defs.bzl", "rust_library")

rust_library(
    name = "antlir2_feature_impl",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "//antlir/antlir2/antlir2_compile:antlir2_compile",
        "//antlir/antlir2/antlir2_depgraph:antlir2_depgraph",
    ],
)
