load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")

oncall("antlir")

# Install image features to enable auto login of root on the serial console.
feature.new(
    name = "autologin",
    features = [
        [
            feature.install(
                src = "autologin-root.conf",
                dst = "/usr/lib/systemd/system/serial-getty@{}.service.d/autologin-root.conf".format(tty),
            ),
            feature.ensure_subdirs_exist(
                into_dir = "/usr/lib/systemd/system",
                mode = "a+rx,u+w",
                subdirs_to_create = "serial-getty@{}.service.d".format(tty),
            ),
        ]
        # Let's spam on all potential console names as we are only adding a
        # drop-in.
        for tty in [
            "ttyS0",
            "ttyAMA0",
        ]
    ],
    visibility = ["PUBLIC"],
)
