load("//antlir/bzl:oss_shim.bzl", "thrift_library")

thrift_library(
    name = "example",
    languages = ["rust"],
    thrift_srcs = {"example.thrift": None},
    visibility = ["//metalos/lib/state:state-unittest"],
)
