[package]
name = "serde_starlark"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Serde serializer for generating syntactically correct Python code"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[[bin]]
name = "starlark_test"
path = "test/starlark_test.rs"
test = false

[dependencies]
maplit = "1.0"
serde = { version = "1.0.126", features = ["derive", "rc"] }
