[package]
name = "thrift_compiler"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Calls fbthrift compiler to produce unified lib.rs from thrift files"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[[bin]]
name = "compiler"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = "2.33"
