load("//antlir/antlir2/features:defs.bzl", "feature_impl")

oncall("antlir")

feature_impl(
    name = "install",
    deps = [
        "anyhow",
        "base64",
        "hex",
        "serde_json",
        "serde_with",
        "walkdir",
        "xattr",
        "//antlir/antlir2/antlir2_users:antlir2_users",
        "//antlir/antlir2/libcap:libcap"
    ]
)
