# @noautodeps

load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "disk_wipe",
    srcs = ["src/disk_wipe.rs"],
    test_deps = ["fbsource//third-party/rust:rand"],
    unittests = [
        "vm",
    ],
    deps = [
        "anyhow",
        "//metalos/lib/disk:metalos_disk",
    ],
)
