load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/features/dot_meta:dot_meta.bzl", "dot_meta")
load("//antlir/antlir2/image_command_alias:image_command_alias.bzl", "image_command_alias")

oncall("antlir")

feature.new(
    name = "dot-meta",
    features = [
        dot_meta(),
    ],
    visibility = ["PUBLIC"],
)

image.layer(
    name = "skopeo-layer",
    features = [
        feature.rpms_install(
            rpms = [
                "skopeo",
            ]
        ),
    ],
)

image_command_alias(
    name = "skopeo",
    exe = "/usr/bin/skopeo",
    layer = ":skopeo-layer",
    rootless = True,
    visibility = ["PUBLIC"],
)
