load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/features/dot_meta:dot_meta.bzl", "dot_meta")

oncall("antlir")

feature.new(
    name = "dot-meta",
    features = [
        dot_meta(),
    ],
    visibility = ["PUBLIC"],
)
