load("//metalos:defs.bzl", "rust_binary")

# This binary is useful to manually check what a host config generator would
# produce for a given host input, without having to boot a physical server or go
# through vmtest
# Usage:
#   construct a host json input (by hand or download it from the proxy service in facebook/service)
#   buck run //metalos/host_configs:evaluator -- host.json path/to/generator.star
rust_binary(
    name = "evaluator",
    srcs = ["src/evaluator.rs"],
    visibility = [],
    deps = [
        "anyhow",
        "serde_json",
        "slog",
        "slog_glog_fmt",
        "structopt",
        "//metalos/host_configs/evalctx:evalctx",
    ],
)
