[package]
name = "sorted_vector_map"
version = "0.1.0"
authors = ["Facebook <opensource+crates-sorted-vector-map@fb.com>"]
edition = "2018"
description = "maps and sets backed by sorted vectors"
readme = "README.md"
repository = "https://github.com/facebookexperimental/rust-shed"
license = "MIT OR Apache-2.0"
keywords = ["map", "set"]
categories = ["data-structures"]

[[bench]]
name = "map"
harness = false

[[bench]]
name = "set"
harness = false

[dependencies]
itertools = "0.10.1"
quickcheck = "0.9"

[dev-dependencies]
minibench = { version = "0.1.0", git = "https://github.com/facebookexperimental/eden.git", branch = "master" }
