load("//antlir/bzl:build_defs.bzl", "rust_library")

rust_library(
    name = "antlir2_compile",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "thiserror",
        "tracing",
        "//antlir/buck2/features:features",
        "//antlir/staging/antlir2/antlir2_users:antlir2_users",
    ],
)
