["etc/group"]
op = 'diff'

["etc/group".diff]
text-patch = '''
--- parent
+++ child
@@ -1 +1,2 @@
 root:x:0:
+antlir:x:1000:antlir
'''

["etc/passwd"]
op = 'diff'

["etc/passwd".diff]
text-patch = '''
--- parent
+++ child
@@ -1 +1,2 @@
 root:x:0:0:root:/root:/bin/bash
+antlir:x:1000:1000::/:/fakeshell
'''

["etc/shadow"]
op = 'added'

["etc/shadow".diff]
mode = ''
file-type = 'regular-file'
user = 'root'
group = 'root'
text = '''
antlir:!!:::::::
'''
