["etc/group"]
op = 'diff'

["etc/group".diff]
text-patch = '''
--- parent
+++ child
@@ -1 +1,2 @@
 root:x:0:
+antlir:x:1:antlir
'''

["etc/passwd"]
op = 'diff'

["etc/passwd".diff]
text-patch = '''
--- parent
+++ child
@@ -1 +1,2 @@
 root:x:0:0:root:/root:/bin/bash
+antlir:x:1:1::/:/fakeshell
'''

["etc/shadow"]
op = 'diff'

["etc/shadow".diff]
text-patch = '''
--- parent
+++ child
@@ -1 +1,2 @@
 root:!!:::::::
+antlir:!!:::::::
'''
