load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

oncall("antlir")

image.layer(
    name = "base",
    features = [
        feature.ensure_dirs_exist(
            dirs = "/etc",
        ),
        feature.install(
            src = "//antlir/antlir2/test_images:passwd",
            dst = "/etc/passwd",
            mode = "a+r,u+w",
        ),
        feature.install(
            src = "//antlir/antlir2/test_images:group",
            dst = "/etc/group",
            mode = "a+r,u+w",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/fakeshell",
            mode = "a+rx",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "add-user-and-group",
    features = [
        feature.user_add(
            home_dir = "/",
            primary_group = "antlir",
            shell = "/fakeshell",
            username = "antlir",
        ),
        feature.group_add(
            groupname = "antlir",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "add-user-and-group-test",
    diff = "add-user-and-group.toml",
    diff_type = "file",
    layer = ":add-user-and-group",
)

image.layer(
    name = "add-user-to-group",
    features = [
        feature.usermod(
            add_supplementary_groups = ["root"],
            username = "antlir",
        ),
    ],
    parent_layer = ":add-user-and-group",
)

image_diff_test(
    name = "add-user-to-group-test",
    diff = "add-user-to-group.toml",
    diff_type = "file",
    layer = ":add-user-to-group",
)

image.layer(
    name = "base-with-shadow",
    features = [
        feature.install(
            src = "shadow",
            dst = "/etc/shadow",
            mode = "a+",
        ),
    ],
    parent_layer = ":base",
)

image.layer(
    name = "add-user-and-group-existing-shadow",
    features = [
        feature.user_add(
            home_dir = "/",
            primary_group = "antlir",
            shell = "/fakeshell",
            username = "antlir",
        ),
        feature.group_add(
            groupname = "antlir",
        ),
    ],
    parent_layer = ":base-with-shadow",
)

image_diff_test(
    name = "add-user-and-group-existing-shadow-test",
    diff = "add-user-and-group-existing-shadow.toml",
    diff_type = "file",
    layer = ":add-user-and-group-existing-shadow",
)
