[package]
name = "async_compression"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "This crate adds Compressor and Decompressor wrappers around some common libraries"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = { version = "0.4", features = ["serde"] }
bzip2 = { version = "0.3", features = ["tokio"] }
flate2 = { version = "1.0", features = ["rust_backend", "tokio"], default-features = false }
futures = "0.1.31"
tokio-io = "0.1"
zstd = "=0.8.0+zstd.1.4.9"

[dev-dependencies]
assert_matches = "1.5"
quickcheck = "0.9"
rand = { version = "0.7", features = ["small_rng"] }
tokio = "0.1"
