load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/test_images/package:defs.bzl", "test_in_layer")

oncall("antlir")

package.erofs(
    name = "standard.erofs",
    layer = "//antlir/antlir2/test_images/package:standard",
)

test_in_layer(
    name = "test-erofs",
    layer_features = [
        feature.ensure_dirs_exist(dirs = "/package"),
        feature.install(
            src = ":standard.erofs",
            dst = "/package.erofs",
        ),
        feature.rpms_install(rpms = ["erofs-fuse"]),
    ],
    stub = "stub.rs",
)
