load("//antlir/bzl:build_defs.bzl", "cxx_genrule", "export_file", "python_library", "python_unittest")

oncall("antlir")

export_file(
    name = "rename_shadowed.c",
    # This file has to be visible to anything that uses the genrule
    # `image_build_librename_shadowed` layer.  Since we don't know
    # what those uses could be, we have to just make it public.
    visibility = ["PUBLIC"],
)

# Unlike the prod compilation in `librename_shadowed.bzl`, this test-only
# compilation does not use the container's C compiler, but we hope the
# ambient compiler is new enough that this is fine.
#
# Keep (mostly) in sync with `librename_shadowed.bzl` -- just omit
# `-fvisibility=hidden` so that tests can access internal functions.
cxx_genrule(
    name = "librename_shadowed_for_test.so",
    out = "unused",
    cmd = '''
        $(cc) -shared -o "$OUT" -Wall -Werror -O2 \\
            -ldl -fPIC $(location :rename_shadowed.c)
    ''',
)

python_library(
    name = "testlib_librename_shadowed.so",
    resources = {
        ":librename_shadowed_for_test.so": "tests/librename_shadowed.so",
    },
)

python_unittest(
    name = "test-rename-shadowed-internals",
    srcs = ["tests/test_rename_shadowed_internals.py"],
    deps = [
        ":testlib_librename_shadowed.so",
        "//antlir:fs_utils",
    ],
)
