load("//antlir/bzl:constants.bzl", "REPO_CFG")
load("//antlir/bzl:image.bzl", "image")

image.layer(
    name = "base",
    features = [
        # @oss-disable: "//metalos/services/base/facebook:features", 
    ],
    parent_layer = REPO_CFG.artifact["metalos.layer.base"],
    visibility = ["PUBLIC"],
)
