load("@prelude//:rules.bzl", "constraint_setting")
load(":defs.bzl", "os_version")

oncall("antlir")

constraint_setting(
    name = "os",
    visibility = ["PUBLIC"],
)

os_version(
    name = "none",
    family = "//antlir/antlir2/os/family:family[none]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[none]",
)

os_version(
    name = "centos10",
    family = "//antlir/antlir2/os/family:family[centos]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "centos8",
    family = "//antlir/antlir2/os/family:family[centos]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "centos9",
    family = "//antlir/antlir2/os/family:family[centos]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "eln",
    family = "//antlir/antlir2/os/family:family[fedora]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf5]",
)

os_version(
    name = "rhel8",
    family = "//antlir/antlir2/os/family:family[rhel]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "rhel8.8",
    family = "//antlir/antlir2/os/family:family[rhel]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "rhel9",
    family = "//antlir/antlir2/os/family:family[rhel]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "rhel9.2",
    family = "//antlir/antlir2/os/family:family[rhel]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "almalinux9",
    family = "//antlir/antlir2/os/family:family[rhel]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[dnf]",
)

os_version(
    name = "debian-trixie",
    family = "//antlir/antlir2/os/family:family[debian]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[apt]",
)

os_version(
    name = "ubuntu-noble",
    family = "//antlir/antlir2/os/family:family[debian]",
    package_manager = "//antlir/antlir2/os/package_manager:package_manager[apt]",
)
