load("@prelude//:rules.bzl", "constraint_setting")
load(":defs.bzl", "os_version")

constraint_setting(
    name = "os",
    visibility = ["PUBLIC"],
)

os_version(
    name = "none",
    family = "//antlir/antlir2/os/family:none",
)

os_version(
    name = "centos8",
    family = "//antlir/antlir2/os/family:centos",
)

os_version(
    name = "centos9",
    family = "//antlir/antlir2/os/family:centos",
)

os_version(
    name = "eln",
    family = "//antlir/antlir2/os/family:fedora",
)
