load("//antlir/antlir2/bzl:platform.bzl", "arch_select")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

oncall("antlir")

image.layer(
    name = "base",
    features = [
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "select-inside-feature",
    features = [
        feature.install(
            src = arch_select(
                aarch64 = "src.aarch64",
                x86_64 = "src.x86_64",
            ),
            dst = "/arch",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "select-inside-feature-test",
    diff = arch_select(
        aarch64 = "select.aarch64.toml",
        x86_64 = "select.x86_64.toml",
    ),
    diff_type = "file",
    layer = ":select-inside-feature",
)

feature.new(
    name = "install.aarch64",
    features = [
        feature.install(
            src = "src.aarch64",
            dst = "/arch",
        ),
    ],
)

feature.new(
    name = "install.x86_64",
    features = [
        feature.install(
            src = "src.x86_64",
            dst = "/arch",
        ),
    ],
)

image.layer(
    name = "select-feature-target",
    features = [
        arch_select(
            aarch64 = ":install.aarch64",
            x86_64 = ":install.x86_64",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "select-feature-target-test",
    diff = arch_select(
        aarch64 = "select.aarch64.toml",
        x86_64 = "select.x86_64.toml",
    ),
    diff_type = "file",
    layer = ":select-feature-target",
)
