load("//antlir/bzl:build_defs.bzl", "rust_binary", "rust_library")

rust_library(
    name = "repo_proxy",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "derivative",
        "http",
        "hyper",
        "hyper-tls",
        "once_cell",
        "regex",
        "serde",
        "serde_json",
        "thiserror",
        "tokio",
        "tokio-util",
        "tracing",
        "uuid",
        "//antlir/rpm/dnf_conf:dnf_conf",
    ],
)

rust_binary(
    name = "repo-proxy",
    srcs = ["bin/main.rs"],
    deps = [
        "anyhow",
        "clap-3",
        "serde_json",
        "tokio",
        "tracing-glog",
        "tracing-subscriber",
        ":repo_proxy",
    ],
)
