load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")

oncall("antlir")

feature.new(
    name = "features",
    features = [
        feature.apt_install(
            packages = [
                "apt",
                "base-files",
                "dpkg",
                "mount",
                "python3",
                "python3-apt",
            ]
        ),
    ],
    visibility = [
        "//antlir/antlir2/build_appliance:features",
    ],
)
