load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "metalos_disk",
    srcs = ["src/lib.rs"],
    unittests = [
        "vm",
    ],
    deps = [
        "anyhow",
        "delegate",
        "nix",
    ],
)
