load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "metalos_disk",
    srcs = ["src/lib.rs"],
    test_deps = [
        "maplit",
    ],
    unittests = [
        "vm",
    ],
    deps = [
        "anyhow",
        "delegate",
        "nix",
        "//metalos/lib/udev_utils:udev_utils",
    ],
)
