load("//metalos:defs.bzl", "rust_library")

rust_library(
    name = "metalos_disk",
    srcs = ["src/lib.rs"],
    test_deps = [
        "maplit",
        "slog_glog_fmt",
    ],
    unittests = [
        "vm",
    ],
    deps = [
        "anyhow",
        "delegate",
        "nix",
        "slog",
    ],
)
