load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl/genrule/locale:locale.bzl", "image_build_locale_archive")
load("//antlir/bzl/image/feature:defs.bzl", "feature")

oncall("twimage")

image_build_locale_archive(
    name = "build-multiple-locales",
    locales = [
        "en_US.utf8",
        "en_CA.utf8",
    ],
    parent_layer = "//antlir/compiler/test_images:test-layer",
)

image_build_locale_archive(
    name = "build-single-locale",
    locales = ["en_US.utf8"],
    parent_layer = "//antlir/compiler/test_images:test-layer",
)

image.layer(
    name = "custom-locales-layer",
    features = [
        feature.clone(
            dest_path = "/multiple-locale-archive",
            src_layer = ":build-multiple-locales",
            src_path = "/locale-archive",
        ),
        feature.clone(
            dest_path = "/single-locale-archive",
            src_layer = ":build-single-locale",
            src_path = "/locale-archive",
        ),
    ],
    parent_layer = "//antlir/compiler/test_images:test-layer",
)

image.python_unittest(
    name = "test-locales",
    srcs = ["test_locales.py"],
    layer = ":custom-locales-layer",
)
