load("//antlir/antlir2/features:defs.bzl", "feature_impl")

oncall("antlir")

feature_impl(
    name = "clone",
    unstable_features = [
        "io_error_more",
    ],
    deps = [
        "anyhow",
        "walkdir",
        "//antlir/antlir2/antlir2_facts:antlir2_facts",
    ],
)
