load("//antlir/bzl:shape.bzl", "shape")

shape.impl(
    name = "install.shape",
    deps = [
        "//antlir/bzl:target_tagger.shape",
    ],
)

shape.impl(
    name = "remove.shape",
)

shape.impl(
    name = "requires.shape",
)

shape.impl(
    name = "usergroup.shape",
)

shape.impl(
    name = "tarball.shape",
    deps = [
        "//antlir/bzl:target_tagger.shape",
    ],
)

shape.impl(
    name = "symlink.shape",
    deps = [
        "//antlir/bzl:target_tagger.shape",
    ],
)
