load("//antlir/bzl:defs.bzl", "fake_macro_library")

fake_macro_library(
    name = "usergroup",
    srcs = ["usergroup.bzl"],
    deps = [
        "//antlir/bzl:shape",
        "//antlir/bzl:target_tagger",
    ],
)
