# @oss-disable
load("//antlir/antlir2/bzl:platform.bzl", "arch_select")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")
load("//antlir/antlir2/testing:image_test.bzl", "image_python_test", "image_rust_test")
load("//antlir/antlir2/testing:query_test.bzl", "query_test")
load("//antlir/bzl:build_defs.bzl", "buck_genrule", "export_file", "python_binary", "rust_binary")

oncall("antlir")

image.layer(
    name = "base",
    features = [],
)

image.layer(
    name = "install-file",
    features = [
        feature.install(
            src = "hello.txt",
            dst = "/hello",
            mode = "a+rw",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-install-file",
    diff = "install-file.toml",
    diff_type = "file",
    layer = ":install-file",
)

image.layer(
    name = "install-text",
    features = [
        feature.install_text(
            dst = "/hello",
            mode = "a+rw",
            text = "Hello world!\n",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-install-text",
    diff = "install-file.toml",
    diff_type = "file",
    layer = ":install-text",
)

image.layer(
    name = "install-with-ids",
    features = [
        feature.install_text(
            dst = "/hello",
            group = 43,
            mode = "a+rw",
            text = "Hello world!\n",
            user = 42,
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-install-with-ids",
    diff = "install-with-ids.toml",
    diff_type = "file",
    layer = ":install-with-ids",
)

buck_genrule(
    name = "genrule-dir",
    out = "out",
    cmd = """
      mkdir $OUT
      mkdir $OUT/foo
      touch $OUT/foo/bar
      echo "I am bar" > $OUT/foo/bar
    """,
)

image.layer(
    name = "install-dir",
    features = [
        feature.install(
            src = ":genrule-dir",
            dst = "/installed-dir/",
            mode = "a+rw,u+w",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-install-dir",
    diff = "install-dir.toml",
    diff_type = "file",
    layer = ":install-dir",
)

image.layer(
    name = "child-image-install-dir",
    features = [
        # Create a subdir underneath a dir that exists
        # at least one level below the top of `:genrule-dir`.
        # This verifies that the dep graph is aware of sub-dirs
        # coming in implicitly.
        feature.ensure_subdirs_exist(
            into_dir = "/installed-dir/foo",
            subdirs_to_create = "child",
        ),
    ],
    parent_layer = ":install-dir",
)

image_diff_test(
    name = "test-child-image-install-dir",
    diff = "child-image-install-dir.toml",
    diff_type = "file",
    layer = ":child-image-install-dir",
)

buck_genrule(
    name = "genrule-dir-with-symlinks",
    out = "out",
    cmd = """
      mkdir $OUT
      ln -s /foo $OUT/bar
      ln -s baz $OUT/qux
    """,
)

image.layer(
    name = "install-dir-with-symlinks",
    features = [
        feature.install(
            src = ":genrule-dir-with-symlinks",
            dst = "/installed-dir/",
            mode = "a+rw,u+w",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-install-dir-with-symlinks",
    diff = "install-dir-with-symlinks.toml",
    diff_type = "file",
    layer = ":install-dir-with-symlinks",
)

# use a fresh binaries that we know will not have already been materialized for
# some other use case
rust_binary(
    name = "true-rs",
    srcs = ["true.rs"],
    crate_root = "true.rs",
    unittests = False,
)

# hide that this is a binary using an export_file, otherwise antlir2 will apply
# the binary split debuginfo feature
export_file(
    name = "true-rs.unstripped",
    src = ":true-rs",
)

python_binary(
    name = "true-py",
    srcs = ["true.py"],
    main_module = "antlir.antlir2.features.install.tests.true",
)

image.layer(
    name = "installed-binary",
    features = [
        feature.rpms_install(
            rpms = [
                "bash",
                "coreutils",
                "gdb",
                # @oss-disable
                "python3",
            ],
        ),
        feature.install(
            src = ":true-rs",
            dst = "/usr/bin/true-rs",
        ),
        feature.install(
            src = ":true-rs.unstripped",
            dst = "/usr/bin/true-rs.unstripped",
        ),
        feature.install(
            src = ":true-py",
            dst = "/usr/bin/true-py",
        ),
    ],
)

image_python_test(
    name = "test-installed-binary",
    srcs = ["test_installed_binary.py"],
    layer = ":installed-binary",
    supports_static_listing = False,
)

image.layer(
    name = "installed-binary-with-gnu-debuglink",
    features = [
        feature.rpms_install(
            rpms = [
                "bash",
                "binutils",
                # @oss-disable
                "python3",
            ],
        ),
        feature.ensure_dirs_exist(dirs = "/foo"),
        feature.install(
            src = ":true-rs",
            always_use_gnu_debuglink = True,
            dst = "/foo/true-rs",
            split_debuginfo = True,
        ),
    ],
)

image_python_test(
    name = "test-installed-gnu-debuglink",
    srcs = ["test_installed_gnu_debuglink.py"],
    # @oss-disable
    layer = ":installed-binary-with-gnu-debuglink",
    supports_static_listing = False,
)

export_file(
    name = "true.precompiled",
    src = arch_select(
        aarch64 = "true.precompiled.aarch64",
        x86_64 = "true.precompiled.x86_64",
    ),
)

buck_genrule(
    name = "deterministic-binary",
    cmd = "cp --reflink=auto $(location :true.precompiled) $OUT",
    executable = True,
)

# precompiled binary so that image_diff_test can be used to validate the split
# debug info support
image.layer(
    name = "deterministic-split-debuginfo",
    features = [
        feature.install(
            src = ":deterministic-binary",
            dst = "/true",
            never_use_dev_binary_symlink = True,
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-deterministic-split-debuginfo",
    diff = select({
        "ovr_config//cpu:arm64": "deterministic-split-debuginfo.aarch64.toml",
        "ovr_config//cpu:x86_64": "deterministic-split-debuginfo.x86_64.toml",
    }),
    diff_type = "file",
    layer = ":deterministic-split-debuginfo",
)

image.layer(
    name = "deterministic-binary-layer",
    features = [
        feature.install(
            src = ":deterministic-binary",
            dst = "/true",
            never_use_dev_binary_symlink = True,
            split_debuginfo = False,
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-deterministic-binary",
    diff = select({
        "ovr_config//cpu:arm64": "deterministic-binary.aarch64.toml",
        "ovr_config//cpu:x86_64": "deterministic-binary.x86_64.toml",
    }),
    diff_type = "file",
    layer = ":deterministic-binary-layer",
)

buck_genrule(
    name = "large-source",
    out = "large-source",
    cmd = """
        head -c 512M </dev/urandom >$OUT
    """,
    visibility = [],
)

image.layer(
    name = "reflink-test-layer",
    features = [
        feature.rpms_install(rpms = ["basesystem"]),
        feature.install(
            src = ":large-source",
            dst = "/installed",
        ),
    ],
)

image_rust_test(
    name = "test-install-uses-reflink-copy",
    srcs = ["test_install_uses_reflink_copy.rs"],
    compatible_with = [
        "ovr_config//os:linux",
    ],
    crate_root = "test_install_uses_reflink_copy.rs",
    layer = ":reflink-test-layer",
    deps = [
        "bitflags",
        "nix",
    ],
)

image.layer(
    name = "install-file-xattr",
    features = [
        feature.install(
            src = "hello.txt",
            dst = "/hello",
            mode = "a+rw",
            xattrs = {
                "user.bar": "0x626172",
                "user.baz": "0sYmF6",
                "user.foo": "foo",
            },
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-install-file-xattr",
    diff = "install-file-xattr.toml",
    diff_type = "file",
    layer = ":install-file-xattr",
)

image.layer(
    name = "install-dir-xattr",
    features = [
        feature.install(
            src = ":genrule-dir",
            dst = "/installed-dir/",
            mode = "a+rw,u+w",
            xattrs = {
                "user.bar": "0x626172",
                "user.baz": "0sYmF6",
                "user.foo": "foo",
            },
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-install-dir-xattr",
    diff = "install-dir-xattr.toml",
    diff_type = "file",
    layer = ":install-dir-xattr",
)

image.layer(
    name = "setcap",
    features = [
        feature.install(
            src = ":deterministic-binary",
            dst = "/caps",
            never_use_dev_binary_symlink = True,
            setcap = "cap_setuid,cap_setgid+ep",
            split_debuginfo = False,
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "test-setcap",
    diff = select({
        "ovr_config//cpu:arm64": "setcap.aarch64.toml",
        "ovr_config//cpu:x86_64": "setcap.x86_64.toml",
    }),
    diff_type = "file",
    layer = ":setcap",
)

query_test(
    name = "test-feature-deps",
    contains = [
        "//antlir/antlir2/features/install:install",
    ],
    excludes = [
        # random features that should definitely not be deps
        "//antlir/antlir2/features/remove:remove",
        "//antlir/antlir2/features/rpm:rpm",
    ],
    query = "deps(:install-file, 2)",
)
