load("@bazel_skylib//lib:paths.bzl", "paths")
load("//antlir/bzl:constants.bzl", "REPO_CFG")
load("//antlir/bzl:hoist.bzl", "hoist")
load("//antlir/bzl:image.bzl", "image")
load("//antlir/bzl:kernel_shim.bzl", "kernels")
load("//antlir/bzl:oss_shim.bzl", "buck_genrule")
load("//antlir/bzl:systemd.bzl", "systemd")
load("//antlir/bzl/genrule/extractor:extract.bzl", "extract")
load("//antlir/bzl/image/feature:defs.bzl", "feature")
load("//antlir/bzl/image/package:defs.bzl", "package")
load("//antlir/bzl/linux:defs.bzl", "linux")
load("//metalos:defs.bzl", "rust_binary")

rust_binary(
    name = "metalos-bootloader",
    srcs = ["metalos_bootloader.rs"],
    # set some flags for a more size-optimized and statically-linked binary
    link_style = "static",
    linker_flags = [
        "-Wl,--strip-all",
    ],
    nodefaultlibs = True,
    rustc_flags = [
        "-C",
        "opt-level=z",
    ],
    deps = [
        "anyhow",
        "nix",
        "slog",
        "slog_glog_fmt",
        "tokio",
        "//metalos/host_configs/rust:metalos_host_configs",
        "//metalos/lib/blkid:blkid",
        "//metalos/lib/kexec:metalos_kexec",
        "//metalos/lib/metalos_paths:metalos_paths",
        "//metalos/lib/state:state",
    ],
)

image.layer(
    name = "with-metalos-bootloader",
    features = [
        feature.install(
            ":metalos-bootloader",
            "/usr/bin/metalos-bootloader",
            mode = "a+rx",
            wrap_as_buck_runnable = False,
        ),
    ],
    parent_layer = REPO_CFG.artifact["metalos.layer.base"],
)

# Use the default kernel as the base for the EFI bootloader for two reasons:
# 1) compiling the kernel is slow and requires a large git clone
# 2) we can count on some small amount of support if we're using an official
#  kernel
KERNEL = kernels.default

image.layer(
    name = "initrd",
    features = [
        extract.extract(
            binaries = ["/usr/bin/metalos-bootloader"],
            source = ":with-metalos-bootloader",
        ),
        systemd.install_unit("metalos-bootloader.service"),
        feature.remove("/usr/lib/systemd/system/initrd.target"),
        systemd.install_unit("metalos-bootloader.target"),
        systemd.set_default_target(
            "metalos-bootloader.target",
            force = True,
        ),
        feature.remove("/usr/lib/initrd-release"),
        linux.release.install(
            layer = ":initrd",
            os_name = "MetalOS",
            path = "/usr/lib/os-release",
            variant = "Bootloader",
        ),
        feature.ensure_subdirs_exist(
            "/usr/lib",
            paths.join(
                "modules",
                KERNEL.uname,
            ),
        ),
        feature.install(
            KERNEL.derived_targets.disk_boot_modules,
            paths.join(
                "/usr/lib/modules",
                KERNEL.uname,
            ),
        ),
    ],
    parent_layer = "//metalos/initrd:initrd-common",
)

package.new(
    name = "initrd.cpio.gz",
    format = "cpio.gz",
    layer = ":initrd",
)

# man 7 systemd-stub
hoist(
    name = "systemd-stub",
    layer = REPO_CFG.artifact["metalos.layer.base"],
    path = "/usr/lib/systemd/boot/efi/linuxx64.efi.stub",
)

buck_genrule(
    name = "bootloader.efi",
    out = "out",
    cmd = """
        objcopy \
            --add-section .osrel="$(location :initrd__os-release)" --change-section-vma .osrel=0x20000 \
            --add-section .linux="$(location {vmlinuz})" --change-section-vma .linux=0x2000000 \
            --add-section .initrd="$(location :initrd.cpio.gz)" --change-section-vma .initrd=0x3000000 \
            "$(location :systemd-stub)" $OUT
    """.format(
        vmlinuz = KERNEL.derived_targets.vmlinuz,
    ),
)
