load("//antlir/antlir2/features:defs.bzl", "feature_impl")
load("//antlir/bzl:build_defs.bzl", "rust_binary")

oncall("antlir")

feature_impl(
    name = "extract",
    deps = [
        "anyhow",
        "goblin",
        "once_cell",
        "regex",
        "serde_json",
        "twox-hash",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/antlir2/antlir2_path:antlir2_path",
    ],
)

rust_binary(
    name = "extract-analyze",
    srcs = ["extract_analyze.rs"],
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "nix",
        "serde_json",
        "tracing",
        "tracing-subscriber",
        ":extract.lib",
        "//antlir/antlir2/antlir2_compile:antlir2_compile",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/antlir2/antlir2_path:antlir2_path",
        "//antlir/antlir2/antlir2_rootless:antlir2_rootless",
    ],
)
