# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//antlir/bzl:build_defs.bzl", "buck_sh_binary", "export_file")

oncall("antlir")

buck_sh_binary(
    name = "makecache",
    main = "makecache.py",
)

export_file(
    name = "makecache.py",
    visibility = [
        "//antlir/antlir2/package_managers/dnf/rules/makecache/...",
    ],
)
