load("//antlir/bzl:shape.bzl", "shape")

oncall("antlir")

shape.impl(
    name = "btrfs.shape",
    deps = [
        "//antlir/bzl:loopback_opts.shape",
        "//antlir/bzl:target.shape",
    ],
)
