load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/features/rpm/tests:defs.bzl", "expected_t", "test_rpms")
load("//antlir/antlir2/package_managers/dnf/rules:repo.bzl", "repo_set")
load("//antlir/antlir2/testing:image_test.bzl", "image_python_test")
load("//antlir/bzl:build_defs.bzl", "internal_external")

oncall("antlir")

repo_set(
    name = "test-repo-set",
    repo_sets = ["//bot_generated/antlir/rpm/fast_snapshot/by_flavor:centos8"],
    repos = ["//antlir/antlir2/features/rpm/tests/repo:test-repo"],
)

_RPM_DEPS_OF_TEST = [
    "dnf",
    "rpm",
    # @oss-disable
]

test_rpms(
    name = "install-modular-rpm",
    dnf_additional_repos = [
        "//antlir/antlir2/features/rpm/tests/repo:test-repo",
    ],
    expected = expected_t(
        installed_module = ["nodejs"],
    ),
    features = [
        feature.rpms_install(
            rpms = [
                "nodejs",
            ] + _RPM_DEPS_OF_TEST,
        ),
    ],
    labels = internal_external(
        fb = [],
        oss = ["disabled"],
    ),
)

image.layer(
    name = "simple",
    features = [
        feature.rpms_install(rpms = _RPM_DEPS_OF_TEST),
    ],
    labels = internal_external(
        fb = [],
        oss = ["disabled"],
    ),
)

image_python_test(
    name = "test-db-backend",
    srcs = ["test_db_backend.py"],
    labels = internal_external(
        fb = [],
        oss = ["disabled"],
    ),
    layer = ":simple",
)
