#!/bin/bash
set -e

# This is a wrapper script for the buck build tool binary.  This will first check
# to see if the actual buck binary needs to be downloaded and if so, will attempt
# to do so from the Antlir S3 bucket, where we have prebuilt artifacts for buck.

resolve_path() {
  local path="$1"
  pushd . > /dev/null
  if cd -P "$path" 2> /dev/null; then
    pwd
  fi
  popd > /dev/null
}

repo_root_dir() {
  CWD="$(resolve_path "$(pwd)")"
  while [[ "$CWD" != "/" ]]; do
    if [[ -e "$CWD"/.buckversion ]]; then
      echo "$CWD"
      return
    fi
    CWD=$(dirname "$CWD")
  done
}

# Derive the actual buck binary location
_repo_root="$(repo_root_dir)"
# Keep the buck binary under .tools/ so it is moderately hidden, but not liable
# to be wiped out by the buckd lifecycle
_buck_bin_dir="${_repo_root}/.tools"

source "${_repo_root}/.buckversion"

BUCK="${_buck_bin_dir}/buck-${BUCK_VERSION}-java11.pex"

run_buck() {
  "${BUCK}" "${@}"
  exit $?
}

BUCK_BASE_URL="https://antlir.s3.us-east-2.amazonaws.com/bin/buck"
get_buck() {
  # Download a the requested version directly from our s3 bucket
  mkdir -p "${_buck_bin_dir}"
  pushd "${_buck_bin_dir}" > /dev/null
  curl -o "${BUCK}.download" \
    "${BUCK_BASE_URL}/buck-${BUCK_VERSION}-java11.pex"
  ret="$?"
  if [ "${ret}" == "0" ]; then
    # Make it executable
    chmod +x "${BUCK}.download"
    # Move it in place
    mv "${BUCK}.download" "${BUCK}"
    popd > /dev/null
  else
    echo "Error downloading new buck version!!"
    rm "${BUCK}.download"
    popd > /dev/null
    exit 1
  fi
}

if [[ ! -f "${BUCK}" ]]; then
  echo "No buck ${BUCK} found! Downloading..."
  get_buck
fi

run_buck "${@}"
