load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")
load(":features.bzl", "tarball_feature_contents")

oncall("antlir")

image.layer(
    name = "base",
    features = [
        feature.rpms_install(rpms = ["bash"]),
        feature.user_add(
            home_dir = "/",
            primary_group = "antlir",
            shell = "/bin/bash",
            uidmap = "antlir",
            username = "antlir",
        ),
        feature.group_add(
            groupname = "antlir",
            uidmap = "antlir",
        ),
        feature.ensure_dirs_exist(
            dirs = "/dir",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/target",
            mode = "a+rx",
        ),
    ],
)

image.layer(
    name = "input-tar-layer",
    features = [
        tarball_feature_contents("/"),
    ],
)

package.tar(
    name = "tar",
    dot_meta = False,
    layer = ":input-tar-layer",
    rootless = True,
)

package.tar_gz(
    name = "tar.gz",
    dot_meta = False,
    layer = ":input-tar-layer",
    rootless = True,
)

package.tar_zst(
    name = "tar.zst",
    dot_meta = False,
    layer = ":input-tar-layer",
    rootless = True,
)

image.layer(
    name = "tar-with-leading-layer",
    features = [
        feature.ensure_dirs_exist(dirs = "/leading/second"),
        tarball_feature_contents("/leading/second"),
    ],
)

package.tar(
    name = "tar-with-leading",
    dot_meta = False,
    layer = ":tar-with-leading-layer",
    rootless = True,
)

image.layer(
    name = "tarball",
    features = [
        feature.tarball(
            src = ":tar",
            into_dir = "/tar",
        ),
        feature.tarball(
            src = ":tar.gz",
            into_dir = "/tar.gz",
        ),
        feature.tarball(
            src = ":tar.zst",
            into_dir = "/tar.zst",
        ),
        feature.tarball(
            src = ":tar",
            force_root_ownership = True,
            into_dir = "/tar_force_root_ownership",
        ),
        feature.tarball(
            src = ":tar-with-leading",
            into_dir = "/tar_strip_2_components",
            strip_components = 2,
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "tarball-test",
    diff = "tarball.toml",
    diff_type = "file",
    layer = ":tarball",
)

image.layer(
    name = "with-xattrs-tar-layer",
    features = [
        feature.install_text(
            dst = "/with-xattrs",
            text = "\n",
            xattrs = {"user.foo": "bar"},
        ),
    ],
)

package.tar(
    name = "with-xattrs.tar",
    dot_meta = False,
    layer = ":with-xattrs-tar-layer",
    rootless = True,
)

image.layer(
    name = "install-with-xattrs",
    features = [
        feature.tarball(
            src = ":with-xattrs.tar",
            into_dir = "/",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "with-xattrs-test",
    diff = "with-xattrs.toml",
    diff_type = "file",
    layer = ":install-with-xattrs",
)
