[package]
name = "futures_ext"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "future crate extensions"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
futures = { version = "0.3.13", features = ["async-await", "compat"] }
pin-project = "0.4"
shared_error = { version = "0.1.0", path = "../shared_error" }
thiserror = "1.0"
tokio_shim = { version = "0.1.0", path = "../tokio_shim" }

[dev-dependencies]
assert_matches = "1.5"
async-stream = "0.3"
tokio = { version = "0.2.25", features = ["full", "test-util"] }
