load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/test_images/package:defs.bzl", "test_in_layer")

oncall("antlir")

package.tar(
    name = "test.tar",
    layer = "//antlir/antlir2/test_images/package:standard",
)

test_in_layer(
    name = "test-tar",
    layer_features = [
        feature.ensure_dirs_exist(dirs = "/package"),
        feature.install(
            src = ":test.tar",
            dst = "/package.tar",
        ),
        feature.rpms_install(rpms = ["tar"]),
    ],
    stub = "stub.rs",
)
