load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

oncall("antlir")

image.layer(
    name = "base",
    features = [
        feature.install(
            src = "//antlir:empty",
            dst = "/a",
        ),
        feature.ensure_dirs_exist(
            dirs = "/b",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/b/c",
        ),
    ],
)

image.layer(
    name = "remove",
    features = [
        feature.remove(path = "/a"),
        feature.remove(path = "/b"),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "remove-test",
    diff = "remove.toml",
    diff_type = "file",
    layer = ":remove",
)

image.layer(
    name = "remove-and-reinstall",
    features = [
        feature.remove(path = "/a"),
        feature.install(
            src = "//antlir:empty",
            dst = "/a",
        ),
        feature.remove(path = "/b"),
        feature.ensure_dirs_exist(dirs = "/b"),
        feature.install(
            src = "//antlir:empty",
            dst = "/b/d",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "remove-and-reinstall-test",
    diff = "remove-and-reinstall.toml",
    diff_type = "file",
    layer = ":remove-and-reinstall",
)

image.layer(
    name = "remove-symlink-parent",
    features = [
        feature.install(
            src = "//antlir:empty",
            dst = "/foo",
        ),
        feature.ensure_file_symlink(
            link = "/bar",
            target = "/foo",
        ),
    ],
)

image.layer(
    name = "remove-symlink",
    features = [feature.remove(path = "/bar")],
    parent_layer = ":remove-symlink-parent",
)

image_diff_test(
    name = "remove-symlink-test",
    diff = "remove-symlink.toml",
    diff_type = "file",
    layer = ":remove-symlink",
)

image.layer(
    name = "remove-under-symlink-parent",
    features = [
        feature.ensure_dirs_exist(dirs = "/foo/bar"),
        feature.ensure_dir_symlink(
            link = "/foo/baz",
            target = "/foo/bar",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/foo/bar/qux",
        ),
    ],
)

image.layer(
    name = "remove-under-symlink",
    features = [feature.remove(path = "/foo/bar/qux")],
    parent_layer = ":remove-under-symlink-parent",
)

image_diff_test(
    name = "remove-under-symlink-test",
    diff = "remove-under-symlink.toml",
    diff_type = "file",
    layer = ":remove-under-symlink",
)
