load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "buck_version",
    srcs = ["src/lib.rs"],
    test_deps = ["serde_json"],
    deps = [
        "clap-3",
        "serde",
        "thiserror",
    ],
)
