load("//antlir/bzl:build_defs.bzl", "rust_library")

rust_library(
    name = "antlir2-package-lib",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "bytesize",
        "serde",
    ],
)
