load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/test_images/package:defs.bzl", "test_in_layer")
load("//antlir/bzl:build_defs.bzl", "python_unittest")

oncall("antlir")

package.ext3(
    name = "default.ext3",
    layer = "//antlir/antlir2/test_images/package:standard",
)

package.ext3(
    name = "size_mb.ext3",
    layer = "//antlir/antlir2/test_images/package:standard",
    size_mb = 1024,
)

package.ext3(
    name = "free_mb.ext3",
    free_mb = 256,
    layer = "//antlir/antlir2/test_images/package:standard",
)

image.layer(
    name = "empty",
    features = [],
)

package.ext3(
    name = "empty.ext3",
    layer = ":empty",
)

python_unittest(
    name = "test-sizing",
    srcs = ["test_sizing.py"],
    resources = {
        ":default.ext3": "default.ext3",
        ":empty.ext3": "empty.ext3",
        ":free_mb.ext3": "free_mb.ext3",
        ":size_mb.ext3": "size_mb.ext3",
    },
)

test_in_layer(
    name = "test-ext3",
    layer_features = [
        feature.ensure_dirs_exist(dirs = "/package"),
        feature.install(
            src = ":default.ext3",
            dst = "/package.ext3",
        ),
        feature.rpms_install(rpms = ["e2fsprogs"]),
    ],
    stub = "stub.rs",
)
