load("//antlir/bzl:build_defs.bzl", "rust_binary")

rust_binary(
    name = "image-rpms-test",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "anyhow",
        "clap",
        "itertools",
        "once_cell",
        "regex",
        "similar-asserts",
        "size",
        "tracing",
        "tracing-glog",
        "tracing-subscriber",
    ],
)
