load("//antlir/bzl:build_defs.bzl", "rust_binary")

rust_binary(
    name = "antlir2_vm",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "anyhow",
        "clap",
        "once_cell",
        "serde",
        "serde_json",
        "thiserror",
        "tracing",
        "tracing-subscriber",
        "//antlir:find_root",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/filesystem/absolute_path:absolute_path",
    ],
)
