load("@prelude//utils:buckconfig.bzl", "read_bool")
load("//antlir/bzl:build_defs.bzl", "is_facebook", "rust_library")

oncall("antlir")

# Modefiles are extremely infectious and end up breaking the exec platform when
# building things for MacOS, despite the execution platform still being Linux.
# As a workaround until the dependencies are fixed (who knows when that'll
# happen), make some deps optional
mac_mode = read_bool(
    "fbcode",
    "mode_mac_enabled",
    default = False,
    required = False,
)

win_mode = read_bool(
    "fbcode",
    "mode_win_enabled",
    default = False,
    required = False,
)

linux = not mac_mode and not win_mode

rust_library(
    name = "antlir2_working_volume",
    srcs = glob(["src/**/*.rs"]),
    compatible_with = [
        "ovr_config//os:freebsd",
        "ovr_config//os:linux",
        "ovr_config//os:macos",
    ],
    fb_deps = [
        "//common/rust/shed/fbinit:fbinit",
    ] + ([
        "//common/rust/fbwhoami:fbwhoami",
        "//common/rust/scuba:scuba",
        "//common/rust/shed/scuba_sample:scuba_sample",
    ] if linux else []),
    rustc_flags = [
        "--cfg=scuba",
    ] if (linux and is_facebook) else [],
    deps = [
        "nix",
        "thiserror",
        "tracing",
        "uuid",
        "//antlir/antlir2/antlir2_btrfs:antlir2_btrfs",
    ],
)
