load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir2_working_volume",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "nix",
        "thiserror",
        "tracing",
        "uuid",
    ],
)
