load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/features/test_only_features:trace.bzl", "trace")
load("//antlir/bzl:build_defs.bzl", "python_unittest")

oncall("antlir")

image.layer(
    name = "layer",
    features = [
        trace(msg = "This feature-internal trace should appear in log files"),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

python_unittest(
    name = "test-feature-trace-appears-in-logs",
    srcs = ["test_feature_trace_appears_in_logs.py"],
    resources = {
        ":layer[debug][compile][logs][compile]": "logs",
    },
)
