load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/features/test_only_features/extend_facts:extend_facts.bzl", "extend_facts")
load("//antlir/bzl:build_defs.bzl", "rust_unittest")

oncall("antlir")

image.layer(
    name = "parent",
    features = [
        extend_facts(msg = "fact logged from parent"),
    ],
)

image.layer(
    name = "child",
    features = [
        extend_facts(msg = "fact logged from child"),
    ],
    parent_layer = ":parent",
)

rust_unittest(
    name = "test-appears-in-facts",
    srcs = ["test_appears_in_facts.rs"],
    resources = {
        "child.db": ":child[debug][facts]",
        "parent.db": ":parent[debug][facts]",
    },
    deps = [
        "buck-resources",
        "serde",
        "tracing",
        "tracing-test",
        "//antlir/antlir2/antlir2_facts:antlir2_facts",
    ],
)
