load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/bzl:build_defs.bzl", "buck_genrule", "python_unittest")

oncall("antlir")

buck_genrule(
    name = "parent_large_file",
    out = "parent_large_file",
    cmd = """
        # it's important that this is properly random so that we don't have to
        # account for compression
        head -c 100M </dev/urandom >$OUT
    """,
    visibility = [],
)

image.layer(
    name = "parent",
    features = [
        feature.install(
            src = ":parent_large_file",
            dst = "/parent_large_file",
        ),
        feature.install_text(
            dst = "/foo",
            text = "foo\n",
        ),
    ],
)

package.sendstream_v2(
    name = "parent.sendstream",
    layer = ":parent",
)

buck_genrule(
    name = "child_large_file",
    out = "child_large_file",
    cmd = """
        # it's important that this is properly random so that we don't have to
        # account for compression
        head -c 10M </dev/urandom >$OUT
    """,
    visibility = [],
)

image.layer(
    name = "child",
    features = [
        feature.install(
            src = ":child_large_file",
            dst = "/child_large_file",
        ),
        feature.install_text(
            dst = "/bar",
            text = "bar\n",
        ),
    ],
    parent_layer = ":parent",
)

package.sendstream_v2(
    name = "child.sendstream",
    incremental_parent = ":parent.sendstream",
    layer = ":child",
)

image.layer(
    name = "foo",
    features = [
        feature.install_text(
            dst = "/foo",
            text = "foo",
        ),
    ],
)

python_unittest(
    name = "test-incremental-size",
    srcs = ["test_incremental_size.py"],
    resources = {
        ":child.sendstream": "child.sendstream",
        ":parent.sendstream": "parent.sendstream",
    },
)
