load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/antlir2/test_images/package:defs.bzl", "package_feature", "test_in_layer")

oncall("antlir")

package.cpio(
    name = "test.cpio",
    layer = "//antlir/antlir2/test_images/package:standard",
)

test_in_layer(
    name = "test-cpio",
    layer_features = [
        feature.ensure_dirs_exist(dirs = "/package"),
        feature.install(
            src = ":test.cpio",
            dst = "/package.cpio",
        ),
        feature.rpms_install(rpms = ["cpio"]),
    ],
    omit_package_features = [package_feature("xattr")],
    stub = "stub.rs",
)
