load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")
load("//antlir/bzl:build_defs.bzl", "python_unittest")

oncall("antlir")

image.layer(
    name = "layer",
    features = [
        feature.install_text(
            dst = "/foo",
            text = "foo\n",
        ),
        feature.ensure_file_symlink(
            link = "/foo-sym",
            target = "/foo",
        ),
    ],
)

package.cpio(
    name = "test.cpio",
    layer = ":layer",
)

python_unittest(
    name = "test-cpio",
    srcs = ["test.py"],
    resources = {
        ":test.cpio": "test.cpio",
    },
)
