load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir_mount",
    srcs = ["src/lib.rs"],
    compatible_with = [
        "ovr_config//os:freebsd",
        "ovr_config//os:linux",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "mockall",
        "nix",
        "proc-mounts",
        "thiserror",
        "tracing",
        "//metalos/antlir_image/antlir_image:antlir_image",
    ],
)
