load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir_mount",
    srcs = glob(["src/**/*.rs"]),
    compatible_with = [
        "ovr_config//os:freebsd",
        "ovr_config//os:linux",
    ],
    test_deps = [
        "maplit",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "mockall",
        "nix",
        "proc-mounts",
        "thiserror",
        "tracing",
    ],
)
