load("//antlir/antlir2/antlir2_vm/bzl:disk.bzl", "vm_disk")
load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/bzl/package:btrfs.bzl", "BtrfsSubvol")
load("//antlir/antlir2/bzl/package:defs.bzl", "package")

oncall("antlir")

image.layer(
    name = "foo",
    features = [
        feature.install_text(
            dst = "/foo",
            text = "foo",
        ),
    ],
)

image.layer(
    name = "bar",
    features = [
        feature.install_text(
            dst = "/bar",
            text = "bar",
        ),
    ],
)

image.layer(
    name = "qux",
    features = [
        feature.install_text(
            dst = "/qux",
            text = "qux",
        ),
    ],
)

package.btrfs(
    name = "btrfs",
    default_subvol = "/foo/baz/qux",
    label = "mylabel",
    subvols = {
        "/bar": BtrfsSubvol(
            layer = ":bar",
            writable = True,
        ),
        "/foo": BtrfsSubvol(layer = ":foo"),
        "/foo/baz/qux": BtrfsSubvol(
            layer = ":qux",
        ),
    },
)

package.btrfs(
    name = "btrfs-seed",
    default_subvol = "/foo/baz/qux",
    label = "seed",
    seed_device = True,
    subvols = {
        "/bar": BtrfsSubvol(
            layer = ":bar",
            writable = True,
        ),
        "/foo": BtrfsSubvol(layer = ":foo"),
        "/foo/baz/qux": BtrfsSubvol(
            layer = ":qux",
        ),
    },
)

FREE_MB = 1024

package.btrfs(
    name = "btrfs-free-space",
    default_subvol = "/foo/baz/qux",
    free_mb = FREE_MB,
    label = "free-space",
    subvols = {
        "/bar": BtrfsSubvol(
            layer = ":bar",
            writable = True,
        ),
        "/foo": BtrfsSubvol(layer = ":foo"),
        "/foo/baz/qux": BtrfsSubvol(
            layer = ":qux",
        ),
    },
)

vm_disk(
    name = "test-disk",
    base_image = ":btrfs",
    bootable = False,
    visibility = [
        "//antlir/antlir2/test_images/package/btrfs/...",
    ],
)

vm_disk(
    name = "seed-disk",
    base_image = ":btrfs-seed",
    bootable = False,
    visibility = [
        "//antlir/antlir2/test_images/package/btrfs/...",
    ],
)

vm_disk(
    name = "free-space-disk",
    base_image = ":btrfs-free-space",
    bootable = False,
    visibility = [
        "//antlir/antlir2/test_images/package/btrfs/...",
    ],
)
