load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

oncall("twimage")

image.layer(
    name = "base",
    features = [
        feature.ensure_dirs_exist(
            dirs = "/dir",
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/target",
            mode = "a+rx",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "symlink",
    features = [
        feature.ensure_dir_symlink(
            link = "/symlink-to-dir",
            target = "/dir",
        ),
        feature.ensure_file_symlink(
            link = "/dir/symlink-to-file",
            target = "/target",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "symlink-test",
    diff = "symlink.toml",
    diff_type = "file",
    layer = ":symlink",
)
