load("//antlir/bzl:build_defs.bzl", "rust_library")

oncall("antlir")

rust_library(
    name = "antlir2_mode",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "rstest",
    ],
    deps = [
        "nom",
    ],
)
