load("//antlir/antlir2/features:defs.bzl", "feature_impl")

oncall("antlir")

feature_impl(
    name = "rpm",
    deps = [
        "memfd",
        "serde_json",
        "//antlir/antlir2/antlir2_isolate:antlir2_isolate",
        "//antlir/buck/buck_label:buck_label",
    ],
)
