load("//antlir/bzl:build_defs.bzl", "export_file")
load("//antlir/bzl/image/feature:defs.bzl", "feature")
load("//antlir/bzl/linux:defs.bzl", "linux")

oncall("antlir")

export_file(
    name = "eth0.link",
    visibility = ["PUBLIC"],
)

export_file(
    name = "eth0.network",
    visibility = ["PUBLIC"],
)

export_file(
    name = "etc-hosts",
    visibility = ["PUBLIC"],
)

export_file(
    name = "require-udevd.conf",
    visibility = ["PUBLIC"],
)

# empty resolv.conf since the only mechanism to refer to the host (by name) is via /etc/hosts
feature.new(
    name = "resolvconf",
    features = [
        linux.config.network.resolv.install(
            nameservers = [],
            search_domains = [],
        ),
    ],
    visibility = ["PUBLIC"],
)
