[package]
name = "services_common"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Common code for stubbed facebook services"
readme = "../../README.md"
homepage = "https://github.com/facebookexperimental/rust-shed/"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
error-chain = "0.12"
