[package]
name = "fbinit"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Facebook init token"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[lib]
test = false
doctest = false

[[test]]
name = "fbinit_test"
path = "test/fbinit_test.rs"

[dependencies]
macros = { version = "0.1.0", path = "macros" }
quickcheck = "0.9"

[dev-dependencies]
fbinit-tokio-02 = { version = "0.1.0", path = "fbinit-tokio-02" }
