load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")
load("//antlir/bzl:build_defs.bzl", "is_facebook", "rust_binary")

oncall("twimage")

image.layer(
    name = "base",
    features = [
        feature.rpms_install(
            rpms = [
                "bash",
                "coreutils",
                "systemd",
            ],
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/empty",
        ),
        feature.install(
            src = "genrule.sh",
            dst = "/genrule.sh",
            mode = "a+rx",
        ),
        feature.install(
            src = "genrule-with-repo.sh",
            dst = "/genrule-with-repo.sh",
            mode = "a+rx",
        ),
        feature.install(
            src = ":needs-platform",
            dst = "/binary-genrule",
        ),
        # This is stupid, but the systemd-nspawn performed by 'genrule' dumps a
        # ton of other junk (ex P717441612) into the image and I want my diff
        # test to just show the things that my "interesting" genrule did, not
        # implementation details of systemd-nspawn
        feature.genrule(
            bind_repo_ro = True,
            cmd = ["true"],
            user = "root",
        ),
    ] + ([
        feature.install(
            src = "//antlir:empty",
            dst = "/is-facebook",
        ),
    ] if is_facebook else []),
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "genrule",
    features = [
        feature.genrule(
            bind_repo_ro = True,
            cmd = [
                "/genrule.sh",
                "$(location //antlir:empty)",
            ],
            user = "root",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "genrule-test",
    diff = "genrule.toml",
    diff_type = "file",
    layer = ":genrule",
)

image.layer(
    name = "genrule-with-repo",
    features = [
        feature.genrule(
            bind_repo_ro = True,
            cmd = [
                "/genrule-with-repo.sh",
            ],
            user = "root",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "genrule-with-repo-test",
    diff = "genrule-with-repo.toml",
    diff_type = "file",
    layer = ":genrule-with-repo",
)

image.layer(
    name = "genrule-without-repo",
    features = [
        feature.genrule(
            bind_repo_ro = False,
            cmd = [
                "/genrule-with-repo.sh",
            ],
            user = "root",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "genrule-without-repo-test",
    diff = "genrule-without-repo.toml",
    diff_type = "file",
    layer = ":genrule-without-repo",
)

rust_binary(
    name = "needs-platform",
    srcs = ["bin.rs"],
    crate_root = "bin.rs",
    unittests = False,
)

image.layer(
    name = "genrule-with-platform",
    features = [
        feature.genrule(
            cmd = [
                "/binary-genrule",
            ],
            mount_platform = True,
            user = "root",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "genrule-with-platform-test",
    diff = "genrule-with-platform.toml",
    diff_type = "file",
    layer = ":genrule-with-platform",
)
