load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")

image.layer(
    name = "base",
    features = [
        feature.rpms_install(
            rpms = [
                "bash",
                "coreutils",
                "systemd",
            ],
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/empty",
        ),
        feature.install(
            src = "genrule.sh",
            dst = "/genrule.sh",
            mode = "a+rx",
        ),
        # This is stupid, but the systemd-nspawn performed by 'genrule' dumps a
        # ton of other junk (ex P717441612) into the image and I want my diff
        # test to just show the things that my "interesting" genrule did, not
        # implementation details of systemd-nspawn
        feature.genrule(
            cmd = ["true"],
            user = "root",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "genrule",
    features = [
        feature.genrule(
            cmd = ["/genrule.sh"],
            user = "root",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "genrule-test",
    diff = "genrule.toml",
    diff_type = "file",
    layer = ":genrule",
)
