load("//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/testing:image_diff_test.bzl", "image_diff_test")
load("//antlir/bzl:build_defs.bzl", "rust_binary")

rust_binary(
    name = "genrule-rs",
    srcs = ["genrule.rs"],
    crate_root = "genrule.rs",
    unittests = False,
)

image.layer(
    name = "base",
    features = [
        feature.rpms_install(
            rpms = [
                "bash",
                "coreutils",
                "systemd",
            ],
        ),
        feature.install(
            src = "//antlir:empty",
            dst = "/empty",
        ),
        feature.install(
            src = "genrule.sh",
            dst = "/genrule.sh",
            mode = "a+rx",
        ),
        feature.install(
            src = ":genrule-rs",
            dst = "/genrule-rs",
            mode = "a+rx",
        ),
    ],
    flavor = "//antlir/antlir2/test_images:test-image-flavor",
)

image.layer(
    name = "genrule",
    features = [
        feature.genrule(
            cmd = ["/genrule.sh"],
            user = "root",
        ),
        feature.genrule(
            cmd = ["/genrule-rs"],
            user = "root",
        ),
    ],
    parent_layer = ":base",
)

image_diff_test(
    name = "genrule-test",
    diff = "genrule.toml",
    layer = ":genrule",
)
