[file.empty]
op = 'removed'

[file.empty.diff]
mode = 'u+r,g+r,o+r'
file-type = 'regular-file'
user = 'root'
group = 'root'
text = ''

[file.empty-copied-from-location-macro]
op = "added"

[file.empty-copied-from-location-macro.diff]
mode = "u+rw,g+r,o+r"
file-type = "regular-file"
user = "root"
group = "root"
text = ""

[file.foo]
op = 'added'

[file.foo.diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = 'root'
group = 'root'
content_hash = "0"

[file."foo/bar"]
op = 'added'

[file."foo/bar".diff]
mode = 'u+rwx,g+rx,o+rx'
file-type = 'directory'
user = 'root'
group = 'root'
content_hash = "0"

[file."foo/bar/baz"]
op = 'added'

[file."foo/bar/baz".diff]
mode = 'u+rw,g+r,o+r'
file-type = 'regular-file'
user = 'root'
group = 'root'
text = '''
qux
'''
