load("//antlir/bzl:oss_shim.bzl", "rust_library")

oncall("twimage")

rust_library(
    name = "buck_query",
    srcs = [
        "lib.rs",
        "query.rs",
        "targets.rs",
    ],
    deps = [
        "anyhow",
        "serde",
        "serde_json",
    ],
)
