load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")
load("//antlir/antlir2/bzl/image:defs.bzl", "image")
load("//antlir/antlir2/features/test_only_features/supplements:supplements.bzl", "supplements")
load("//antlir/bzl:build_defs.bzl", "python_unittest")
load(":dump_supplements.bzl", "dump_supplements")

oncall("antlir")

image.layer(
    name = "parent",
    features = [
        supplements(msg = "parent"),
    ],
)

image.layer(
    name = "child",
    features = [
        supplements(msg = "child"),
    ],
    parent_layer = ":parent",
)

dump_supplements(
    name = "supplements.json",
    layer = ":child",
)

python_unittest(
    name = "test-supplements",
    srcs = ["test_supplements.py"],
    network_access = network_access_utils.all(),
    resources = {
        ":supplements.json": "supplements.json",
    },
)
